---
title: "Nutrient and YSI Data Correlations"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---
# Correlations
## Import Libraries
```{r Import Libraries}
library(tidyverse)
library(lubridate)
library(Hmisc)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999)
```

## Import Data
```{r import data}
# use 03-OceanWaterQualityData-QCCutoff.csv
dfYSI <- read_csv("Data/Clean/YSI/02_QualityControl/02-YSI-Data-QCCutoff.csv")

# use 03-OceanWaterQualityData-QCCutoff.csv
dfNutrients <- read_csv("Data/Clean/Nutrients/02_QualityControl/02-Nutrients-Data-Clean-QC.csv")

```

## Data Formatting
### YSI
```{r data format: ysi}
dfYSI_edit <- dfYSI %>%
  # shorten time series dates to be comparable with Nutrient dates
  filter(date >= "2017-12-01") %>%
  # create year, month, week columns
  mutate(year = year(date)) %>%
  mutate(month = month(date)) %>%
  mutate(week = week(date)) %>%
  # group by year, month, week to take comparisons of each week within the time series
  group_by(year, month, week) %>%
  # take weekly medians to make more comparable to Nutrient data which is taken weekly
  mutate(temp_f = median(temp_f, na.rm = TRUE)) %>%
  mutate(temp_c = median(temp_c, na.rm = TRUE)) %>%
  mutate(pH_ysi = median(pH, na.rm = TRUE)) %>%
  mutate(pH_mV = median(pH_mV, na.rm = TRUE)) %>%
  mutate(salinity_psu = median(salinity_psu, na.rm = TRUE)) %>%
  mutate(conductivity_uScm = median(conductivity_uScm, na.rm = TRUE)) %>%
  mutate(nlf_conductivity_uScm = median(nlf_conductivity_uScm, na.rm = TRUE)) %>%
  mutate(sp_conductivity_uScm = median(sp_conductivity_uScm, na.rm = TRUE)) %>%
  mutate(do_mgL = median(do_mgL, na.rm = TRUE)) %>%
  mutate(do_saturated_percent = median(do_saturated_percent, na.rm = TRUE)) %>%
  mutate(do_local_percent = median(do_local_percent, na.rm = TRUE)) %>%
  mutate(orp_mV = median(orp_mV, na.rm = TRUE)) %>%
  mutate(chlorophyll_rfu = median(chlorophyll_rfu, na.rm = TRUE)) %>%
  mutate(total_algae_rfu = median(total_algae_rfu, na.rm = TRUE)) %>%
  mutate(total_dissolved_solids_mgL = median(total_dissolved_solids_mgL, na.rm = TRUE))%>%
  select(-time, -date, -chlorophyll_ugL, -total_algae_cellsL, -pH) %>%
  distinct() %>%
  mutate(date = paste(year, month, week, sep = "-")) %>%
  ungroup() %>%
  select(-year, -month, -week) %>%
  relocate(date, .before = temp_f)

```
### Nutrients
```{r data format: nutrients}
dfNutrients_edit <- dfNutrients %>%
  # select only data from the ocean
  filter(Location == "Ocean") %>%
  # create year, month, week columns
  mutate(year = year(Date)) %>%
  mutate(month = month(Date)) %>%
  mutate(week = week(Date)) %>%
  # group by year, month, week to take comparisons of each week within the time series
  group_by(year, month, week) %>%
  # take weekly medians to make more comparable to Nutrient data which is taken weekly
  mutate(Turbidity = median(Turbidity, na.rm = TRUE)) %>%
  mutate(Phosphate = median(Phosphate, na.rm = TRUE)) %>%
  mutate(`Nitrate MR` = median(`Nitrate MR`, na.rm = TRUE)) %>%
  mutate(`Nitrate HR` = median(`Nitrate HR`, na.rm = TRUE)) %>%
  mutate(pH_nutrients = median(pH, na.rm = TRUE)) %>%
  mutate(Alkalinity = median(Alkalinity, na.rm = TRUE)) %>%
  mutate(Silica = median(Silica, na.rm = TRUE)) %>%
  mutate(Iron = median(Iron, na.rm = TRUE)) %>%
  select(-Date, -Location, -pH) %>%
  distinct() %>%
  mutate(date = paste(year, month, week, sep = "-")) %>%
  ungroup() %>%
  select(-year, -month, -week) %>%
  relocate(date, .before = Turbidity)


```
### Combine Data
```{r data format: combine data}
# combine dfNutrients_edit and dfYSI_edit, with dfNutrients_edit being first because it has fewer observations
dfNutrientsYSI <- left_join(dfNutrients_edit, dfYSI_edit) %>%
  rename(`Chlorophyll (RFU)` = chlorophyll_rfu,
         `Conductivity (µS/cm)` = conductivity_uScm,
         `Dissolved Oxygen, Local (%)` = do_local_percent,
         `Dissolved Oxygen (mg/L)` = do_mgL,
         `Dissolved Oxygen, Saturated (%)` = do_saturated_percent,
         `Conductivity, Non-Linear Function (µS/cm)` = nlf_conductivity_uScm,
         `Oxygen Reduction Potential (mV)` = orp_mV,
         `pH (mV)` = pH_mV,
         `pH (Nutrients)` = pH_nutrients,
         `pH (YSI)` = pH_ysi,
         `Salinity (PSU)` = salinity_psu,
         `Conductivity, Specific (µS/cm)` = sp_conductivity_uScm,
         `Temperature (ºC)` = temp_c,
         `Temperature (ºF)` = temp_f,
         `Total Algae (RFU)` = total_algae_rfu,
         `Total Dissolved Solids (mg/L)` = total_dissolved_solids_mgL) %>%
select(-date)

```

## Create Correlation Matrices
```{r short: create, format correlation matrices}
# create nested list of matrices: p-values, n, r values
cor_mat_stats <- rcorr(as.matrix(dfNutrientsYSI))

# full flattened correlation matrix
cor_mat_stats_flat <- flattenCorrMatrix(cor_mat_stats$r, cor_mat_stats$P) %>%
  mutate(across(3:4, ~ round(.x, 2))) 
write_csv(cor_mat_stats_flat, 
          file = "Data/Clean/NutrientsYSI/01_Correlations/NutrientsYSI-Correlations.csv")

# flattened correlation matrix with only p-values <= 0.05
cor_mat_stats_flat_sig <- cor_mat_stats_flat %>%
  filter(p_value <= 0.05)
write_csv(cor_mat_stats_flat_sig, 
          file = "Data/Clean/NutrientsYSI/01_Correlations/NutrientsYSI-Correlations-Significant.csv")
  
```

```{r plots}
# Correlogram
{ # open pdf graphics driver
  pdf(file = "Figures/NutrientsYSI/01_Correlations/NutrientsYSI-Correlations-Correlogram.pdf",
      width = 15, height = 10)
  # make correlation plot
  corrplot(cor_mat_stats$r, method = "number", outline = TRUE, type = "full", diag = TRUE,
           order = "original", 
           tl.col = "black", tl.srt = 45, mar = c(5, 5, 5, 5),
           title = "Biosphere 2 Ocean Nutrient and YSI Water Quality Correlations")
  # close graphics driver
  dev.off()
}

# Correlogram with Significance
cor_mat_stats$P[is.na(cor_mat_stats$P)] <- 1 #turn NAs into 1's (insignificant) -- only NA values are on the diagonal (temp_f compared to temp_f etc)
{ # open pdf graphics driver
  pdf(file = "Figures/NutrientsYSI/01_Correlations/NutrientsYSI-Correlations-Correlogram-Significant.pdf",
      width = 13, height = 10)
  corrplot(cor_mat_stats$r, method = "shade", type="full", order="original",
           diag = TRUE,
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 4, 0),
           p.mat = cor_mat_stats$P, sig.level = 0.05, insig = "p-value",
           title = "Biosphere 2 Ocean Nutrient and YSI Water Quality Significant Correlations \n
           P-Values Labeled")
  # close graphics driver
  dev.off()
}

```

