---
title: "YSI Figures Pre-QC"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

```{r Libraries}
library(tidyverse)
library(lubridate)
```

# Import Data
```{r import data}
# Wrangled data before QC -- outliers still present
df <- read_csv("Data/CleanData/CleanData_YSI/01_DataWrangling/01-OceanWaterQualityData.csv")
```
# Data Formatting
```{r Pre-plotting Formatting}
# pivot df longer for easier all-variable plotting
dfPivot <- df %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))

# character vector of variable names as they appear in the dataframes
variable_names <- unique(dfPivot$variable)

# character vector of variable names as they should be written on a graph
variable_text <- c("Temperature (ºF)", "Temperature (ºC)", "pH", "pH (mV)",
                   "Salinity (PSU)", "Conductivity (µS/cm)", 
                   "NLF Conductivity (µS/cm", "Specific Conductivity (µS/cm)",
                   "Dissolved Oxygen (mg/L)", "Dissolved Oxygen, Saturated (%)",
                   "Dissolved Oxygen, Local (%)", "ORP (mV)", "Chlorophyll (RFU)",
                   "Chlorophyll (µg/L)", "Total Algae (RFU)", "Total Algae (cells/L)",
                   "Total Dissolved Solids (mg/L)")


# character vector of file names for plots
file_names <- c("TempFPlot", "TempCPlot", "pHPlot", "pHmVPlot", "SalinityPlot",
                "ConductivityPlot", "NlfConductivityPlot", "SpConductivityPlot",
                "DomglPlot", "DoSatPlot", "DoLocalPlot", "OrpPlot", "ChlorophyllRfuPlot",
                "ChlorophylluglPlot", "TotalAlgaeRfuPlot", "TotalAlgaeCellsLPlot",
                "TotalDissolvedSolidsPlot")

```

# Plotting
## Pre-QC Plots
```{r Basic plots - Pre QC}
# line graph of every variable - facet wrapped 
AllVariablePlot_PreQC <- dfPivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-PreQC.pdf", plot = AllVariablePlot_PreQC, 
       path = "Figures/Figures_YSI/01-PreQCPlots", height = 12, width = 10)


# individual line graphs of each variable
# list to save plots from loop into
plotList_preqc <- list()
# loop through each variable, plot, save
for (i in 1:length(variable_names)) {
plotList_preqc[[i]] <- dfPivot %>%
  filter(variable == variable_names[i]) %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = paste("B2O", variable_text[i], "from 2011-2023"),
       subtitle = "Pre-QC: All Outliers Still Present", 
       x = "Date",
       y = variable_text[i])

print(plotList_preqc[[i]])

# Save plot
ggsave(plot = plotList_preqc[[i]],
       filename = paste(file_names[i],"-PreQC.pdf", sep = ""),
       path = "Figures/Figures_YSI/01-PreQCPlots")
}

```