---
title: "YSI Figures: Correlations"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

# Import Libraries
```{r import libraries}
library(tidyverse)
library(Hmisc)
library(corrplot)
library(PerformanceAnalytics)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999)
```

#Import Data
```{r import data}
# use 03-OceanWaterQualityData-QCCutoff.csv
df <- read_csv("Data/Clean/YSI/02_QualityControl/02-YSI-Data-QCCutoff.csv")
```
# Total Time Series
## Data Formatting
```{r Total: data formatting}
df_corTotal <- df %>%
  # take out columns that will give NA values in correlations (not enough observations)
  select(-date, -time, -chlorophyll_ugL, 
         -total_algae_cellsL, -total_dissolved_solids_mgL) %>%
  rename(`Chlorophyll (RFU)` = chlorophyll_rfu,
         `Conductivity (µS/cm)` = conductivity_uScm,
         `Dissolved Oxygen, Local (%)` = do_local_percent,
         `Dissolved Oxygen (mg/L)` = do_mgL,
         `Dissolved Oxygen, Saturated (%)` = do_saturated_percent,
         `Conductivity, Non-Linear Function (µS/cm)` = nlf_conductivity_uScm,
         `Oxygen Reduction Potential (mV)` = orp_mV,
         `pH (mV)` = pH_mV,
         `Salinity (PSU)` = salinity_psu,
         `Conductivity, Specific (µS/cm)` = sp_conductivity_uScm,
         `Temperature (ºC)` = temp_c,
         `Temperature (ºF)` = temp_f,
         `Total Algae (RFU)` = total_algae_rfu)

```

## Get Significant Statistics
```{r Total: significant stats}
# create nested list of matrices: p-values, n, r values
cor_mat_statsTotal <- rcorr(as.matrix(df_corTotal))

cor_mat_pvalsTotal <- cor_mat_statsTotal$P

# full flattened correlation matrix
cor_mat_stats_flatTotal <- flattenCorrMatrix(cor_mat_statsTotal$r, cor_mat_statsTotal$P) %>%
  mutate(across(3:4, ~ round(.x, 2))) 


```

## Correlation Plots
``` {r Total: cor plots}
# Correlogram
{ # open pdf graphics driver
  pdf(file = "Figures/YSI/04_Correlations/TotalTimeSeries/YSI-Correlations-Correlogram-TotalTimeSeries.pdf", 
      width = 13, height = 13)
  # make correlation plot
  corrplot(cor_mat_statsTotal$r, method = "number", type = "full", diag = TRUE,
           order = "original", 
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 6, 0),
           title = "Biosphere 2 Ocean YSI Water Quality Correlations \n
           Whole Time Series Comparison")
  # close graphics driver
  dev.off()
}

# Correlogram with Significance
cor_mat_statsTotal$P[is.na(cor_mat_statsTotal$P)] <- 1 #turn NAs into 1's (insignificant) -- only NA values are on the diagonal (temp_f compared to temp_f etc)
{ # open pdf graphics driver
  pdf(file = "Figures/YSI/04_Correlations/TotalTimeSeries/YSI-Correlations-Correlogram-Significant-TotalTimeSeries.pdf",
      width = 13, height = 13)
  corrplot(cor_mat_statsTotal$r, method = "number", type="full", order="original", 
           diag = TRUE, 
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 6, 0),
           p.mat = cor_mat_statsTotal$P, sig.level = 0.05, insig = "blank",
           title = "Biosphere 2 Ocean Water Quality Significant Correlations \n
           Whole Time Series Comparison \n
           P-Value < 0.05")
  # close graphics driver
  dev.off()
}

```
# Shortened Time Series
## Data Formatting
```{r Short: data formatting}
df_corShort <- df %>%
  # remove dates before jan 1 2018 to get shortened time series that will acutely compare variables that started to be measured later in time
  filter(date >= "2018-01-01") %>%
  # take out columns that will give NA values in correlations (not enough observations)
  select(-date, -time, -chlorophyll_ugL, -total_algae_cellsL) %>%
  rename(`Chlorophyll (RFU)` = chlorophyll_rfu,
         `Total Dissolved Solids (mg/L)` = total_dissolved_solids_mgL,
         `Conductivity (µS/cm)` = conductivity_uScm,
         `Dissolved Oxygen, Local (%)` = do_local_percent,
         `Dissolved Oxygen (mg/L)` = do_mgL,
         `Dissolved Oxygen, Saturated (%)` = do_saturated_percent,
         `Conductivity, Non-Linear Function (µS/cm)` = nlf_conductivity_uScm,
         `Oxygen Reduction Potential (mV)` = orp_mV,
         `pH (mV)` = pH_mV,
         `Salinity (PSU)` = salinity_psu,
         `Conductivity, Specific (µS/cm)` = sp_conductivity_uScm,
         `Temperature (ºC)` = temp_c,
         `Temperature (ºF)` = temp_f,
         `Total Algae (RFU)` = total_algae_rfu)

```

## Get Significant Statistics
```{r Short: significant stats}
# create nested list of matrices: p-values, n, r values
cor_mat_statsShort <- rcorr(as.matrix(df_corShort))

cor_mat_pvalsShort <- cor_mat_statsShort$P

# full flattened correlation matrix
cor_mat_stats_flatShort <- flattenCorrMatrix(cor_mat_statsShort$r, cor_mat_statsShort$P) %>%
  mutate(across(3:4, ~ round(.x, 2))) 


```

## Correlation Plots
``` {r Short: cor plots}
# Correlogram
{ # open pdf graphics driver
  pdf(file = "Figures/YSI/04_Correlations/ShortenedTimeSeries/YSI-Correlations-Correlogram-ShortenedTimeSeries.pdf", 
      width = 13, height = 13)
  # make correlation plot
  corrplot(cor_mat_statsShort$r, method = "number", type = "full", diag = TRUE,
           order = "original", 
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 6, 0),
           title = "Biosphere 2 Ocean YSI Water Quality Correlations \n
           Shortened Time Series Comparison: 01-01-2018-Present")
  # close graphics driver
  dev.off()
}

# Correlogram with Significance
cor_mat_statsShort$P[is.na(cor_mat_statsShort$P)] <- 1 #turn NAs into 1's (insignificant) -- only NA values are on the diagonal (temp_f compared to temp_f etc)
{ # open pdf graphics driver
  pdf(file = "Figures/YSI/04_Correlations/ShortenedTimeSeries/YSI-Correlations-Correlogram-Significant-ShortenedTimeSeries.pdf",
      width = 13, height = 13)
  corrplot(cor_mat_statsShort$r, method = "number", type="full", order="original", 
           diag = TRUE, 
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 6, 0),
           p.mat = cor_mat_statsShort$P, sig.level = 0.05, insig = "blank",
           title = "Biosphere 2 Ocean Water Quality Significant Correlations \n
           Shortened Time Series Comparison: 01-01-2018-Present \n
           P-Value < 0.05")
  # close graphics driver
  dev.off()
}

```
