---
title: "Exos Notebook"
Collaborators: Dan Killam, Aidan Kavanaugh, Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

```{r Import Libraries}
library(data.table)
library(tidyverse)
library(stringi)
library(lubridate)
library(dplyr)
library(tsibble)
library(tibbletime)

# note: I prefer the package tsibble which includes some new features. tibbletime is actually retired. but tsibble was having trouble parsing the time column for some reason. it is more tempermental. there is also a timetk package I haven't used as much

```


```{r Read in files, format}
#file path for your data directory. might work with the "Box Sync" client as well, haven't tried
path <- "/Users/grambihler/Documents/data/GitHub/OceanWaterQuality/YSI Data/UTF-8 versions" 

# create exoframe: use path to create list of files to read in, read in files in path, specify column data types, skip the first 9 rows, and specify UTF-16 encoding for files from YSI exo sonde
exoframe <- list.files(path = path,
                       pattern = ".csv") %>%
            map_df(~read_csv(.,
                             col_types = cols(.default = col_double(),
                                              `Date (MM/DD/YYYY)` = col_date(format = '%m/%d/%Y'),
                                              `Site Name` = col_character(),
                                              `Time (HH:mm:ss)` = col_time(format = "%H:%M:%S")),
                             skip = 9,
                             locale=locale(encoding="UTF-16")))

```

```{r Data Wrangling}
#bind list entries into single merged data frame
exodata <- rbindlist(exolist,use.names=TRUE,fill=TRUE) 

#rename columns to easier names
colnames(exodata)<-c("Date","Time","Time.fracsec","Sitename","Chlor.RFU","Cond.uScm",
                     "nLF.Cond.uScm","DO.percsat","DO.perclocal","DO.mgL","ORP.mV",
                     "S.PSU","SpCond.uScm","TAL.PE.RFU","TDS.mgL","Wiperpos.V",
                     "pH","pH.mV","TempC","BattV","CablepwrV","filename") 

#I find that R does best when you break up the date column into its parts and put them back together into a date
#break date into its parts
exodata <- exodata %>%
  separate(Date,c("Month","Day","Year"),sep="/") 

#break time into its parts
exodata <- exodata %>%
  separate(Time,c("Hour","Minute","Second"))

#paste them together again and make a date
exodata$Datetime <- ymd_hms(paste(exodata$Year,exodata$Month,exodata$Day,
                                  " ",exodata$Hour,":",exodata$Minute,":",exodata$Second))

#create a date column again
exodata$Date <- as_date(date(exodata$Datetime))

#remove any duplicate rows
exodata <- distinct(exodata)
#remove any NAs
exodata <- subset(exodata,is.na(exodata$Datetime)==FALSE) 

#make any columns that might be stuck as factors numeric
exodata <- exodata %>% 
  mutate_at(c(9:25), as.numeric) 

#create a time tibble
exotbl <- as_tbl_time(exodata,index=Datetime)

#order by day
exotblm<- exotbl %>% 
  arrange(ymd_hms(exotbl$Datetime)) 
```

```{r Data Analysis Syntax Example}
#this syntax can be used to aggregate the data by all sorts of periods including week, hour, etc
exoday<-exotbl %>%
  collapse_by("day") %>%
  group_by(Datetime,Date)%>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))

```

```{r Plot Example}
#create plots for data points
ggplot(exoday,aes(Date,DO.mgL))+
  geom_point(cex=1,alpha=0.5)+
  ylab(expression(paste("pH")))+
  xlab(element_blank())+
  theme_classic(base_size=20)+
  theme(legend.position = "bottom")

```