---
title: "Hach and YSI Data Correlations"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---
# Correlations
## Import Libraries
```{r Import Libraries}
library(tidyverse)
library(lubridate)
library(Hmisc)
library(corrplot)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999)
```

## Import Data
```{r import data}
# use 03-OceanWaterQualityData-QCCutoff.csv
dfYSI <- read_csv("Data/Clean/YSI/02_QualityControl/02-YSI-Data-QCCutoff.csv")

# use 02-Hach-Data-Clean-QC.csv
dfHach <- read_csv("Data/Clean/Hach/02_QualityControl/02-Hach-Data-Clean-QC.csv")

```

## Data Formatting
### YSI
```{r data format: ysi}
dfYSI_edit <- dfYSI %>%
  # shorten time series dates to be comparable with Hach dates
  filter(Date >= "2017-12-01") %>%
  # create year, month, week columns
  mutate(year = year(Date)) %>%
  mutate(month = month(Date)) %>%
  mutate(week = week(Date)) %>%
  # group by year, month, week to take comparisons of each week within the time series
  group_by(year, month, week) %>%
  # take weekly medians to make more comparable to Hach data which is taken weekly
  mutate(`Temperature (ºF)` = median(`Temperature (ºF)`, na.rm = TRUE)) %>%
  mutate(`Temperature (ºC)` = median(`Temperature (ºC)`, na.rm = TRUE)) %>%
  mutate(pH = median(pH, na.rm = TRUE)) %>%
  mutate(`pH (mV)` = median(`pH (mV)`, na.rm = TRUE)) %>%
  mutate(`Salinity (PSU)` = median(`Salinity (PSU)`, na.rm = TRUE)) %>%
  mutate(`Conductivity (µS/cm)` = median(`Conductivity (µS/cm)`, na.rm = TRUE)) %>%
  mutate(`Conductivity, Non-Linear Function (µS/cm)` = median(`Conductivity, Non-Linear Function (µS/cm)`, na.rm = TRUE)) %>%
  mutate(`Conductivity, Specific (µS/cm)` = median(`Conductivity, Specific (µS/cm)`, na.rm = TRUE)) %>%
  mutate(`Dissolved Oxygen (mg/L)` = median(`Dissolved Oxygen (mg/L)`, na.rm = TRUE)) %>%
  mutate(`Dissolved Oxygen, Saturated (%)` = median(`Dissolved Oxygen, Saturated (%)`, na.rm = TRUE)) %>%
  mutate(`Dissolved Oxygen, Local (%)` = median(`Dissolved Oxygen, Local (%)`, na.rm = TRUE)) %>%
  mutate(`Oxygen Reduction Potential (mV)` = median(`Oxygen Reduction Potential (mV)`, na.rm = TRUE)) %>%
  mutate(`Chlorophyll (RFU)` = median(`Chlorophyll (RFU)`, na.rm = TRUE)) %>%
  mutate(`Total Algae (RFU)` = median(`Total Algae (RFU)`, na.rm = TRUE)) %>%
  mutate(`Total Dissolved Solids (mg/L)` = median(`Total Dissolved Solids (mg/L)`, na.rm = TRUE))%>%
  select(-Time, -Date, -`Chlorophyll (µg/L)`, -`Total Algae (cells/L)`) %>%
  distinct() %>%
  mutate(Date = paste(year, month, week, sep = "-")) %>%
  ungroup() %>%
  select(-year, -month, -week) %>%
  relocate(Date, .before = `Temperature (ºF)`)

```
### Hach
```{r data format: Hach}
dfHach_edit <- dfHach %>%
  # select only data from the ocean
  filter(Location == "Ocean") %>%
  # create year, month, week columns
  mutate(year = year(Date)) %>%
  mutate(month = month(Date)) %>%
  mutate(week = week(Date)) %>%
  # group by year, month, week to take comparisons of each week within the time series
  group_by(year, month, week) %>%
  # take weekly medians to make more comparable to Hach data which is taken weekly
  mutate(`Turbidity (RFU)` = median(`Turbidity (RFU)`, na.rm = TRUE)) %>%
  mutate(`Phosphate (mg/L)` = median(`Phosphate (mg/L)`, na.rm = TRUE)) %>%
  mutate(`Nitrate, Mid-Range (mg/L)` = median(`Nitrate, Mid-Range (mg/L)`, na.rm = TRUE)) %>%
  mutate(`Nitrate, High-Range (mg/L)` = median(`Nitrate, High-Range (mg/L)`, na.rm = TRUE)) %>%
  mutate(pH_Hach = median(pH, na.rm = TRUE)) %>%
  mutate(`Alkalinity (mg/L CaCO3)` = median(`Alkalinity (mg/L CaCO3)`, na.rm = TRUE)) %>%
  mutate(`Silica (mg/L)` = median(`Silica (mg/L)`, na.rm = TRUE)) %>%
  mutate(`Iron (mg/L)` = median(`Iron (mg/L)`, na.rm = TRUE)) %>%
  select(-Date, -Location, -pH, -pH_Hach) %>%
  distinct() %>%
  mutate(Date = paste(year, month, week, sep = "-")) %>%
  ungroup() %>%
  select(-year, -month, -week) %>%
  relocate(Date, .before = `Turbidity (RFU)`)


```
### Combine Data
```{r data format: combine data}
# combine dfHach_edit and dfYSI_edit, with dfHach_edit being first because it has fewer observations
dfHachYSI <- left_join(dfHach_edit, dfYSI_edit) %>%
  select(-Date) 
```

## Create Correlation Matrices
```{r short: create, format correlation matrices}
# create nested list of correlation matrices: p-values, n, r values
cor_mat_stats <- rcorr(as.matrix(dfHachYSI))

# full flattened correlation matrix: table of correlation pairings using matrices created in cor_mat_stats
cor_mat_stats_flat <- flattenCorrMatrix(cor_mat_stats$r, cor_mat_stats$P) %>%
  mutate(across(3:4, ~ round(.x, 2))) 

# flattened correlation matrix with only p-values <= 0.05: table of correlation pairings created in cor_mat_stats
cor_mat_stats_flat_sig <- cor_mat_stats_flat %>%
  filter(p_value <= 0.05)
  
```

## Write Correlation Data Files
```{r write files}
# create csv file of correlation matrix of r values
write_csv(as.data.frame(cor_mat_stats$r), 
          file = "Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-RValues.csv")

# create csv file of correlation matrix of p values
write_csv(as.data.frame(cor_mat_stats$P), 
          file = "Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-PValues.csv")

# write csv file of correlation table created in cor_mat_stats_flat, which shows all correlation pairings, their r values, and their pvalues 
write_csv(cor_mat_stats_flat, 
          file = "Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationTable-Total.csv")

# write csv file of correlation table created in cor_mat_stats_flat_sig, which shows all significant correlation pairings (p-value <= 0.05), their r values, and their pvalues
write_csv(cor_mat_stats_flat_sig, 
          file = "Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationTable-Significant.csv")
```

