---
title: "Exos Notebook"
Collaborators: Renee Grambihler, Dan Killam
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

```{r Import Libraries}
library(tidyverse)
library(lubridate)
library(here)
# library(data.table)
# library(stringi)
#library(tsibble)
#library(tibbletime)

# turns scientific notation off
options(scipen = 999)

# note: I prefer the package tsibble which includes some new features. tibbletime is actually retired. but tsibble was having trouble parsing the time column for some reason. it is more tempermental. there is also a timetk package I haven't used as much

```


# Files from various SCADA databases and instruments
## 2011 - 2021
```{r Read in SCADA files from 2011-2021}
# file path to folder containing old scada database 2011-2021 ocean water quality files
path <- "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-sonde-raw-data/SCADA/SCADA-2011-2021"

# data from 7/22/11 - 8/4/14
ocean_data_2011_2014 <- read_csv(here(path, "Ocean_FTP_Data - pre 2014-8-11.csv"),
                                 skip = 1,
                                 col_names = c("datetime",
                                               "temp_f",
                                               "temp_c",
                                               "pH",
                                               "salinity_psu",
                                               "conductivity_uScm",
                                               "orp_mV")) %>%
  mutate(conductivity_uScm = conductivity_uScm*1000) %>%
  na.omit()%>%
  filter(!orp_mV == -999 & !orp_mV == 0) %>%
  add_column(chlorophyll_ugL = NA,
             .after = 7)

# data from 10/3/14 - 6/12/18
ocean_data_2014_2018 <- read_csv(here(path, "Ocean_FTP_Data.csv"), 
                                 skip = 1,
                                 col_names = c("datetime",
                                               "temp_f",
                                               "temp_c",
                                               "pH",
                                               "salinity_psu",
                                               "conductivity_uScm",
                                               "orp_mV")) %>%
  mutate(conductivity_uScm = conductivity_uScm*1000) %>%
  na.omit() %>%
  filter(!orp_mV == -999 & !orp_mV == 0) %>%
  add_column(chlorophyll_ugL = NA,
             .after = 7)

# data from 11/18/16 - 6/12/18
ocean_data_2016_2018 <- read_csv(here(path, "Ocean_FTP_Data_Extended.csv"), 
                                 skip = 1,
                                 col_names = c("datetime",
                                               "temp_f",
                                               "temp_c",
                                               "pH",
                                               "salinity_psu",
                                               "conductivity_uScm",
                                               "orp_mV",
                                               "total_algae_rfu",
                                               "chlorophyll_ugL",
                                               "ro_flow_gpm")) %>%
  mutate(conductivity_uScm = conductivity_uScm*1000)%>%
  na.omit() %>%
  filter(!orp_mV == -999 & !orp_mV == 0)

# data from 10/12/18 - 5/25/21
ocean_data_2018_2021 <- read_csv(here(path, "Ocean_Data_new.csv"), 
                                 skip = 1, 
                                 col_names = c("datetime",
                                               "temp_c",
                                               "pH",
                                               "salinity_psu",
                                               "conductivity_uScm",
                                               "orp_mV",
                                               "total_algae_cellsL",
                                               "chlorophyll_ugL",
                                               "do_saturated_percent"))%>%
  mutate(conductivity_uScm = conductivity_uScm*1000)%>%
  na.omit() %>%
  add_column(temp_f = NA, .after = 1)

```


# Files from old YSI sonde and new YSI EXO3 sonde, downloaded from old B2 SCADA database
## 10/21/19 - 2/23/22
```{r Read in SCADA files from 10/21/19-2/23/22}
# file path to folder containing old scada database 10/21/19-2/23/22 ocean water quality files
path <- "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-sonde-raw-data/SCADA/SCADA-2019-2022"

# total algae phycoerythrin in cells/L from 10/21/19-5/26/21 from old YSI
olddb_ysi_total_algae <- read_csv(here(path,
                                       "UAB2_B240001_YSI_OCEANBGA_PE_593908.csv"),
                                    col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         total_algae_cellsL = VALUE)

# chlorophyll in ug/L from 10/21/19-5/26/21 from old YSI
olddb_ysi_chlorophyll <- read_csv(here(path,
                                       "UAB2_B240001_YSI_OCEANCHLORO_595563.csv"),
                                  col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         chlorophyll_ugL = VALUE)

# electrical conductivity in mS/cm from 10/21/19-5/26/21 from old YSI
olddb_ysi_conductivity <- read_csv(here(path, 
                                        "UAB2_B240001_YSI_OCEANCONDUC_597443.csv"),
                                   col_select = c("TIMESTAMP", "VALUE"))%>%
  mutate(VALUE = VALUE*1000)%>%
  rename(datetime = TIMESTAMP,
         conductivity_uScm = VALUE)

# reduction potential (ORP) in mV from 10/21/19-5/26/21 from old YSI
olddb_ysi_orp <- read_csv(here(path, "UAB2_B240001_YSI_OCEANORP_598894.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         orp_mV = VALUE)

# pH in pH units from 10/21/19-5/26/21 from old YSI
olddb_ysi_pH <- read_csv(here(path, "UAB2_B240001_YSI_OCEANPH_600334.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         pH = VALUE)

# salinity in ppt from 10/21/19-5/26/21 from old YSI
olddb_ysi_salinity <- read_csv(here(path, "UAB2_B240001_YSI_OCEANSALANI_602884.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         salinity_psu = VALUE)

# temperature in degrees Celcius from 10/21/19-5/26/21 from old YSI
olddb_ysi_temp_c <- read_csv(here(path, "UAB2_B240001_YSI_OCEANTMP_604270.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         temp_c = VALUE)

# chlorophyll in RFU from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_chlorophyll <- read_csv(here(path, 
                                       "UAB2_B240001_YSI_EXO3_CHLORO_617107.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         chlorophyll_rfu = VALUE)

# electrical conductivity in uS/cm from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_conductivity <- read_csv(here(path, 
                                        "UAB2_B240001_YSI_EXO3_COND_U_617936.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         conductivity_uScm = VALUE)

# nLF conductivity in uS/cm from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_nlf_conductivity <- read_csv(here(path, 
                                      "UAB2_B240001_YSI_EXO3_NLF_CO_661668.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         nlf_conductivity_uScm = VALUE)

# dissolved oxygen in % local from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_do_local <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_ODO__L_632594.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_local_percent = VALUE)

# dissolved oxygen in % saturated from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_do_saturated <- read_csv(here(path, 
                                        "UAB2_B240001_YSI_EXO3_ODO__S_635338.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_saturated_percent = VALUE)

# dissolved oxygen in mg/L from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_do <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_ODO_MG_645798.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_mgL = VALUE)

# reduction potential (ORP) in mV from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_orp <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_ORP_MV_647084.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         orp_mV = VALUE)

# pH in pH units from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_ph <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_PH_662411.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         pH = VALUE)

# pH in mV from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_ph_mv <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_PH_MV_663459.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         pH_mV = VALUE)

# salinity in psu from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_salinity <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_SAL_PS_647937.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         salinity_psu = VALUE)

# specific conductivity in uS/cm from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_sp_conductivity <- read_csv(here(path, 
                                           "UAB2_B240001_YSI_EXO3_SPCOND_648943.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         sp_conductivity_uScm = VALUE)

# total algae phycoerythrin in RFU from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_total_algae <- read_csv(here(path, 
                                       "UAB2_B240001_YSI_EXO3_TAL_PE_650659.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         total_algae_rfu = VALUE)

# total dissolved solids in mg/L from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_total_dissolved_solids <- read_csv(here(path,
                                          "UAB2_B240001_YSI_EXO3_TDS_MG_653051.csv"),
                                          col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         total_dissolved_solids_mgL = VALUE)

# temperature in degrees Celcius from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_temp_c <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_TEMP_C_655738.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         temp_c = VALUE)

# temperature in degrees Fahrenheit from 5/26/21-2/23/22 from current YSI EXO3 Sonde
olddb_exo_temp_f <- read_csv(here(path, "UAB2_B240001_YSI_EXO3_TEMP_F_659351.csv"),
                                   col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         temp_f = VALUE)

```


# Files from YSI EXO3 Sonde, downloaded from new B2 SCADA database
## 1/22/22 - Present
```{r Read in SCADA files from 1/22/22-present}
# file path to folder containing new scada database 1/22/22-present ocean water quality files
path <- "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-sonde-raw-data/SCADA/SCADA-2022-PRESENT"

# chlorophyll in RFU from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_chlorophyll <- read_csv(here(path,
                              "UAB2_BIO1_B4000_YSI_EXO3_CHLOROPHYLL_RFU_687484.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         chlorophyll_rfu = VALUE)

# electrical conductivity in uS/cm from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_conductivity <- read_csv(here(path, 
                                    "UAB2_BIO1_B4000_YSI_EXO3_COND_USPCM_686791.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         conductivity_uScm = VALUE)

# nLF conductivity in uS/cm from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_nlf_conductivity <- read_csv(here(path, 
                                "UAB2_BIO1_B4000_YSI_EXO3_NLF_COND_USPCM_675074.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         nlf_conductivity_uScm = VALUE)

# dissolved oxygen in % local from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_do_local <- read_csv(here(path, 
                                    "UAB2_BIO1_B4000_YSI_EXO3_ODO__LOCAL_685469.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_local_percent = VALUE)

# dissolved oxygen in % saturated from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_do_saturated <- read_csv(here(path, 
                                    "UAB2_BIO1_B4000_YSI_EXO3_ODO__SAT_683139.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_saturated_percent = VALUE)

# dissolved oxygen in mg/L from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_do <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_ODO_MGPL_684055.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         do_mgL = VALUE)

# reduction potential (ORP) in mV from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_orp <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_ORP_MV_682052.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         orp_mV = VALUE)

# pH in pH units from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_ph <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_PH_673160.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         pH = VALUE)

# pH in mV from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_ph_mv <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_PH_MV_672635.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         pH_mV = VALUE)

# salinity in psu from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_salinity <- read_csv(here(path,
                                    "UAB2_BIO1_B4000_YSI_EXO3_SAL_PSU_682617.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         salinity_psu = VALUE)

# specific conductivity in uS/cm from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_sp_conductivity <- read_csv(here(path, 
                                  "UAB2_BIO1_B4000_YSI_EXO3_SPCOND_USPCM_681325.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         sp_conductivity_uScm = VALUE)

# total algae phycoerythrin in RFU from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_total_algae <- read_csv(here(path, 
                                  "UAB2_BIO1_B4000_YSI_EXO3_TAL_PE_RFU_680581.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         total_algae_rfu = VALUE)

# total dissolved solids in mg/L from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_total_dissolved_solids <- read_csv(here(path,
                                    "UAB2_BIO1_B4000_YSI_EXO3_TDS_MGPL_679560.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         total_dissolved_solids_mgL = VALUE)

# temperature in degrees Celcius from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_temp_c <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_TEMP_C_680104.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         temp_c = VALUE)

# temperature in degrees Fahrenheit from 1/22/22-present from current YSI EXO3 Sonde
newdb_exo_temp_f <- read_csv(here(path, "UAB2_BIO1_B4000_YSI_EXO3_TEMP_F_675540.csv"),
                              skip = 2,
                              col_select = c("TIMESTAMP", "VALUE")) %>%
  rename(datetime = TIMESTAMP,
         temp_f = VALUE)

```


# Data Wrangling
```{r Wrangle and combine data frames}
# create pre-2019 ocean data dataframe
OceanDataFame_2011_2021 <- rbind(ocean_data_2011_2014, 
                              ocean_data_2014_2018,
                              ocean_data_2016_2018[,c(1:7,9)],
                              ocean_data_2018_2021[,c(1:7,9)])%>%
  left_join(ocean_data_2016_2018)%>%
  left_join(ocean_data_2018_2021)

# create old database YSI dataframe by joining the files for each variable from this instrument based on the datetime column
OlddbYsiFrame <- olddb_ysi_temp_c %>%
  left_join(olddb_ysi_pH) %>%
  left_join(olddb_ysi_salinity) %>%
  left_join(olddb_ysi_conductivity) %>%
  left_join(olddb_ysi_orp) %>%
  left_join(olddb_ysi_total_algae) %>%
  left_join(olddb_ysi_chlorophyll)

# create old database YSI EXO3 dataframe by joining the files for each variable from this instrument based on the datetime column
OlddbYsiExoFrame <- olddb_exo_temp_c %>%
  left_join(olddb_exo_ph) %>%
  left_join(olddb_exo_salinity) %>%
  left_join(olddb_exo_conductivity) %>%
  left_join(olddb_exo_orp) %>%
  left_join(olddb_exo_total_algae) %>%
  left_join(olddb_exo_chlorophyll) %>%
  left_join(olddb_exo_do) %>%
  left_join(olddb_exo_do_local) %>%
  left_join(olddb_exo_do_saturated) %>%
  left_join(olddb_exo_nlf_conductivity) %>%
  left_join(olddb_exo_ph_mv) %>%
  left_join(olddb_exo_sp_conductivity) %>%
  left_join(olddb_exo_temp_f) %>%
  left_join(olddb_exo_total_dissolved_solids)

# create new database YSI EXO3 dataframe by joining the files for each variable from this instrument based on the datetime column
NewdbYsiExoFrame <- newdb_exo_temp_c %>%
  left_join(newdb_exo_ph) %>%
  left_join(newdb_exo_salinity) %>%
  left_join(newdb_exo_conductivity) %>%
  left_join(newdb_exo_orp) %>%
  left_join(newdb_exo_total_algae) %>%
  left_join(newdb_exo_chlorophyll) %>%
  left_join(newdb_exo_do) %>%
  left_join(newdb_exo_do_local) %>%
  left_join(newdb_exo_do_saturated) %>%
  left_join(newdb_exo_nlf_conductivity) %>%
  left_join(newdb_exo_ph_mv) %>%
  left_join(newdb_exo_sp_conductivity) %>%
  left_join(newdb_exo_temp_f) %>%
  left_join(newdb_exo_total_dissolved_solids)

# create dataframe of all YSI Exo3 Sonde data
YsiExoFrame <- rbind(OlddbYsiExoFrame, NewdbYsiExoFrame)

# create dataframe of all YSI Sonde data -- 10/21/19-present
YsiFrame <- rbind(OlddbYsiFrame[,1:6], YsiExoFrame[,1:6]) %>%
  left_join(OlddbYsiFrame) %>%
  left_join(YsiExoFrame)

# create dataframe of all data -- 2011-present
# edit column placement of YsiFrame to match up common columns with OceanDataFrame_2011_2021 
YsiFrameEdit <- YsiFrame %>%
  relocate(temp_f, .before = temp_c) %>%
  relocate(chlorophyll_ugL, total_algae_rfu, .after = orp_mV) %>%
  add_column(ro_flow_gpm = NA, .after = 9) %>%
  relocate(do_saturated_percent, .after = total_algae_cellsL)
# combine dataframes, keep unique rows, move columns around so that similar variable are grouped together
OceanWaterQualityFrame <- rbind(OceanDataFame_2011_2021, YsiFrameEdit[, 1:12]) %>%
  left_join(YsiFrameEdit) %>%
  unique() %>%
  relocate(pH_mV, .after = pH) %>%
  relocate(nlf_conductivity_uScm, 
           sp_conductivity_uScm, .after = conductivity_uScm) %>%
  relocate(do_mgL, 
           do_saturated_percent, 
           do_local_percent, .after = sp_conductivity_uScm) %>%
  relocate(chlorophyll_rfu, .after = orp_mV) %>%
  relocate(ro_flow_gpm, .after = total_dissolved_solids_mgL)%>%
  mutate(datetime = ymd_hms(datetime))

#create a time tibble
OceanWaterQualityTibble <- OceanWaterQualityFrame %>%
  as_tbl_time(index = datetime)
#order by day
OceanWaterQualityTibble <- OceanWaterQualityTibble %>% 
  arrange(ymd_hms(datetime))

```


# Preliminary Plotting
```{r Basic plots - pre QC}
# create long format dataframe
# keep NAs in to keep ggplot from connecting across missing data points
OceanWaterQualityFramePivot <- OceanWaterQualityFrame %>%
  pivot_longer(cols = temp_f:ro_flow_gpm,
               names_to = "variable",
               values_to = "variable_value")
  
# line graph of every variable - facet wrapped 
AllVariablePlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_y_continuous(expand = expansion(mult = c(.5, .5))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Water Quality by Variable from 2011-2023") 

AllVariablePlot
# Save plot
ggsave(filename = "AllVariablePlot.png", plot = AllVariablePlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 12, width = 8, units = "in")

# line graph of temp in fahrenheit
TempFPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "temp_f") %>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Temperature(F) from 2011-2023")

TempFPlot
# Save plot
ggsave(filename = "TempFPlot.png", plot = TempFPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of temp in celcius
TempCPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "temp_c")%>%
  filter(variable_value != 0) %>% #removed 0 values because they were messing up averages
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Temperature(C) from 2011-2023")

TempCPlot
# Save plot
ggsave(filename = "TempCPlot.png", plot = TempCPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of pH in pH units
pHPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "pH") %>%
  filter(variable_value != 0) %>% #removed 0 values because they were messing up averages
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(breaks = c(5, 6, 7, 8, 9, 10),
                     expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O pH from 2011-2023")

pHPlot
# Save plot
ggsave(filename = "pHPlot.png", plot = pHPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of pH in mV
pHmVPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "pH_mV") %>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.5, .5))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O pH(mV) from 2021-2023")

pHmVPlot
# Save plot
ggsave(filename = "pHmVPlot.png", plot = pHmVPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of salinity in psu
SalinityPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "salinity_psu")%>%
  mutate(variable_value = ifelse(variable_value < 20, NA, variable_value))%>%         #turn values <20 into NAs because they were messing up averages
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Salinity(psu) from 2011-2023")

SalinityPlot
# Save plot
ggsave(filename = "SalinityPlot.png", plot = SalinityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of conductivity in uS/cm
ConductivityPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "conductivity_uScm") %>%
   # turn values 20000 < x < 60000 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value > 60000, NA, variable_value),
         variable_value = ifelse(variable_value < 20000, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE))%>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Conductivity(uS/cm) from 2011-2023")

ConductivityPlot
# Save plot
ggsave(filename = "ConductivityPlot.png", plot = ConductivityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of nlf conductivity in uS/cm
NLFConductivityPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "nlf_conductivity_uScm") %>%
  filter(date >= "2021-01-01")%>%
  # turn values < 48000 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 48000, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O NLF Conductivity(uS/cm) from 2021-2023")

NLFConductivityPlot
# Save plot
ggsave(filename = "NLFConductivityPlot.png", plot = NLFConductivityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of specific conductivity in uS/cm
SpConductivityPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "sp_conductivity_uScm") %>%
  filter(date >= "2021-01-01")%>%
  # turn values < 48000 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 48000, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Specific Conductivity(uS/cm) from 2021-2023")

SpConductivityPlot
# Save plot
ggsave(filename = "SpConductivityPlot.png", plot = SpConductivityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of DO in mg/L
DOmgLPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "do_mgL") %>%
  filter(date >= "2021-01-01")%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Dissolved Oxygen(mg/L) from 2021-2023")

DOmgLPlot
# Save plot
ggsave(filename = "DOmgLPlot.png", plot = DOmgLPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of DO in percent saturated
DOPercentSaturatedPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "do_saturated_percent") %>%
  filter(date >= "2018-06-01")%>%
  # turn values < 50 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 50, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "6 months") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Dissolved Oxygen(% saturated) from 2018-2023")

DOPercentSaturatedPlot
# Save plot
ggsave(filename = "DOPercentSaturatedPlot.png", plot = DOPercentSaturatedPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of DO in percent local
DOPercentLocalPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "do_local_percent") %>%
  filter(date >= "2021-01-01")%>%
  # turn values < 102 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 102, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Dissolved Oxygen(% local) from 2021-2023")

DOPercentLocalPlot
# Save plot
ggsave(filename = "DOPercentLocalPlot.png", plot = DOPercentLocalPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of ORP in mV
ORPPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "orp_mV") %>%
  # turn values < 102 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 1, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Oxygen Reduction Potential(mV) from 2011-2023")

ORPPlot
# Save plot
ggsave(filename = "ORPPlot.png", plot = ORPPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of chlorophyll in RFU
ChlorophyllRFUPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "chlorophyll_rfu") %>%
  filter(date >= "2021-01-01")%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.5, .5))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Chlorophyll(RFU) from 2021-2023")

ChlorophyllRFUPlot
# Save plot
ggsave(filename = "ChlorophyllRFUPlot.png", plot = ChlorophyllRFUPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of chlorophyll in ug/L
ChlorophyllugLPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "chlorophyll_ugL") %>%
  filter(date >= "2016-06-01")%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Chlorophyll(ug/L) from 2016-2023")

ChlorophyllugLPlot
# Save plot
ggsave(filename = "ChlorophyllugLPlot.png", plot = ChlorophyllugLPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of total algae in cells/L
TotalAlgaePlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "total_algae_cellsL") %>%
  filter(date >= "2018-06-01")%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Total Algae(cells/L) from 2018-2023")

TotalAlgaePlot
# Save plot
ggsave(filename = "TotalAlgaePlot.png", plot = TotalAlgaePlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of total dissolved solids in mg/L
TotalDissolvedSolidsPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "total_dissolved_solids_mgL") %>%
  filter(date >= "2021-01-01")%>%
  # turn values < 31000 into NA so that it doesn't mess up calculations
  mutate(variable_value = ifelse(variable_value < 31000, NA, variable_value))%>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_y_continuous(expand = expansion(mult = c(.1, .1))) +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O Total Dissolved Solids(mg/L) from 2021-2023")

TotalDissolvedSolidsPlot
# Save plot
ggsave(filename = "TotalDissolvedSolidsPlot.png", plot = TotalDissolvedSolidsPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

# line graph of RO flow in gallons/min
ROFlowPlot <- OceanWaterQualityFramePivot %>%
  mutate(date = date(datetime))%>%
  filter(variable == "ro_flow_gpm") %>%
  filter(between(date, as.Date("2016-06-01"), as.Date("2019-01-01"))) %>%
  group_by(date, variable) %>%
  summarise(mean_daily_value = mean(variable_value, na.rm = TRUE)) %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("B2O RO Flow(gallons/minute) from 2016-2018")

ROFlowPlot
# Save plot
ggsave(filename = "ROFlowPlot.png", plot = ROFlowPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures", height = 4, width = 6, units = "in")

  
```


# Original code from Dan (and Renee) for EXO3 files -- can be ignored
```{r Read in and format UTF-16 files}
#file path for your data directory. might work with the "Box Sync" client as well, haven't tried
path16 <- "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-sonde-raw-data/UTF-16-versions" 

# create ExoFrame16: use path to create list of UTF-16 files to read in, read in files in path, specify column data types, skip the first 9 rows, and specify UTF-16 encoding for files from YSI exo sonde
ExoFrame16 <- list.files(path = path16,
                       pattern = ".csv") %>%
            map_df(~read_csv(.,
                             col_types = cols(.default = col_double(),
                                              `Date (MM/DD/YYYY)` = col_date(format = '%m/%d/%Y'),
                                              `Site Name` = col_character(),
                                              `Time (HH:mm:ss)` = col_time(format = "%H:%M:%S")),
                             skip = 9,
                             locale=locale(encoding="UTF-16")))
```

```{r Set Working Directory}
setwd("C:/Users/fried/OneDrive/Desktop/YSI Data") #your data directory. might work with the "Box Sync" client as well, haven't tried
```

```{r File Formatting}
files <- list.files(pattern = ".csv") #create list of files in directory

#bind files into a list. skips the first 8 lines (EXO summary data). creates a column noting the source file of each entry
exolist<-Map(cbind, lapply(files, fread,sep=",",skip=8), filename = files) 

#fread function can't work with the files as they come out of YSI (in UTF-16 format). 
#I had to re-save them in Excel to change them to UTF-8. The YSI outputs should either be converted in bulk in the future, or maybe there's a setting in the KorEXO template.

```

```{r Data Wrangling}
#bind list entries into single merged data frame
exodata <- rbindlist(exolist,use.names=TRUE,fill=TRUE) 

#rename columns to easier names
colnames(exodata)<-c("Date","Time","Time.fracsec","Sitename","Chlor.RFU","Cond.uScm",
                     "nLF.Cond.uScm","DO.percsat","DO.perclocal","DO.mgL","ORP.mV",
                     "S.PSU","SpCond.uScm","TAL.PE.RFU","TDS.mgL","Wiperpos.V",
                     "pH","pH.mV","TempC","BattV","CablepwrV","filename") 

#I find that R does best when you break up the date column into its parts and put them back together into a date
#break date into its parts
exodata <- exodata %>%
  separate(Date,c("Month","Day","Year"),sep="/") 

#break time into its parts
exodata <- exodata %>%
  separate(Time,c("Hour","Minute","Second"))

#paste them together again and make a date
exodata$Datetime <- ymd_hms(paste(exodata$Year,exodata$Month,exodata$Day,
                                  " ",exodata$Hour,":",exodata$Minute,":",exodata$Second))

#create a date column again
exodata$Date <- as_date(date(exodata$Datetime))

#remove any duplicate rows
exodata <- distinct(exodata)
#remove any NAs
exodata <- subset(exodata,is.na(exodata$Datetime)==FALSE) 

#make any columns that might be stuck as factors numeric
exodata <- exodata %>% 
  mutate_at(c(9:25), as.numeric) 

#create a time tibble
exotbl <- as_tbl_time(exodata,index=Datetime)

#order by day
exotblm<- exotbl %>% 
  arrange(ymd_hms(exotbl$Datetime)) 
```

```{r Data Analysis Syntax Example}
#this syntax can be used to aggregate the data by all sorts of periods including week, hour, etc
exoday<-exotbl %>%
  collapse_by("day") %>%
  group_by(Datetime,Date)%>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))

```

```{r Plot Example}
#create plots for data points

ggplot(exoday,aes(Date,DO.mgL))+
ggplot(exoday,aes(Date,pH))+
  geom_point(cex=1,alpha=0.5)+
  ylab(expression(paste("pH")))+
  xlab(element_blank())+
  theme_classic(base_size=20)+
  theme(legend.position = "bottom")


```
