---
title: "Hach and YSI Figures for Paper"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---

```{r import-libraries}
library(tidyverse)
library(lubridate)
library(Hmisc)
library(corrplot)
library(ggcorrplot)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999)
```

```{r import-data}
# time series data
dfTS <- read_csv("Data/Clean/HachYSI/01_DataWrangling/05-HachYSI-Data-All.csv") %>%
  select(-pH_Hach) %>% #take out pH data from Hach
  rename(pH = `pH (YSI)`) #rename pH data from YSI to just pH

# correlation data
## pvalue matrix
matPval <- read_csv("Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-Pvalues.csv")
## rvalue matrix
matRval <- read_csv("Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-RValues.csv")

```

```{r history}
# history plot 
# 1x3: Temp C, Salinity (PSU), pH; 2011-2024
plotHistory <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  # keep just date, temperature celcius, salinity psu, and pH columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH) %>%
  pivot_longer(cols = `Temperature (ºC)`:pH,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)","Salinity (PSU)","pH")))) %>%
  ggplot(aes(x = Date,
             y = var_value)) +
  facet_wrap(~var_name,
             ncol = 1,
             scales = "free_y") +
  geom_line() +
  scale_x_date(date_breaks = "year",
               date_labels = "%Y") +
  ylab("") +
  theme_bw() + 
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())+
        # theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 16),
        #       axis.text.y = element_text(size = 16), 
        #       axis.title.x = element_text(size = 18),
        #       axis.title.y = element_blank(),
        #       plot.title = element_text(size = 20))+
        theme(strip.background = element_rect(fill = "white")) 
  
plotHistory

# Save Plot
ggsave(filename = "HachYSI-1x3HistoryPlot.pdf", 
       plot = plotHistory,
       path = "Figures/HachYSI/02_Paper")


```


```{r env-var}
# environmental variability plot 
# 1x3: Temp C, Salinity (PSU), pH; 2018-2024
plotEnvVar <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  filter(Date >= "2018-01-01") %>%
  # keep just date, temperature celcius, salinity psu, and pH columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH) %>%
  pivot_longer(cols = `Temperature (ºC)`:pH,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)","Salinity (PSU)","pH")))) %>%
  ggplot(aes(x = Date,
             y = var_value)) +
  facet_wrap(~var_name,
             ncol = 1,
             scales = "free_y") +
  geom_line() +
  scale_x_date(date_breaks = "year",
               date_labels = "%Y") +
  ylab("") +
  theme_bw() + 
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())+
        theme(strip.background = element_rect(fill = "white")) 
  
plotEnvVar

# Save Plot
ggsave(filename = "HachYSI-1x3EnvVarPlot.pdf", 
       plot = plotEnvVar,
       path = "Figures/HachYSI/02_Paper")

```

```{r nutrients-water-qual}
# nutrients and water quality plots 
# 2x2: Alkalinity, Nitrate MR, Iron, Silica; 2018-2024 
plotNutWatQual <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  filter(Date >= "2018-01-01") %>%
  # keep just date, alkalinity, nitrate mr, iron, and silica columns
  select(Date, `Alkalinity (mg/L CaCO3)`, `Nitrate, Mid-Range (mg/L)`, `Iron (mg/L)`, `Silica (mg/L)`) %>%
  pivot_longer(cols = `Alkalinity (mg/L CaCO3)`:`Silica (mg/L)`,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Alkalinity (mg/L CaCO3)", "Nitrate, Mid-Range (mg/L)", "Iron (mg/L)", "Silica (mg/L)")))) %>%
  na.omit() %>%
  ggplot(aes(x = Date,
             y = var_value)) +
  facet_wrap(~var_name,
             ncol = 2,
             scales = "free_y") +
  geom_line() +
  geom_smooth() +
  scale_x_date(date_breaks = "year",
               date_labels = "%Y") +
  ylab("") +
  theme_bw() + 
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())+
        theme(strip.background = element_rect(fill = "white")) 
  
plotNutWatQual

# Save Plot
ggsave(filename = "HachYSI-2x2NutWatQualPlot.pdf", 
       plot = plotNutWatQual,
       path = "Figures/HachYSI/02_Paper")


# Correlation Matrix, Significant; 2018-2024 
# change row names of dataframes to be the column names
row_names <- colnames(matPval)
rownames(matPval) <- row_names
rownames(matRval) <- row_names

# turn both dataframes into matrices
matRval <- as.matrix(matRval)
matPval <- as.matrix(matPval)

# turn NAs into insignificant values
matPval[is.na(matPval)] <- 1.00 
matRval[is.na(matRval)] <- 0.00

# Correlogram with Significance
corrPlot_signif <- ggcorrplot(matRval, 
                              p.mat = matPval,
                              outline.color = "white", 
                              ggtheme = ggplot2::theme_gray(), 
                              colors = c("#6D9EC1", "white", "#E46726"), 
                              lab = TRUE,
                              insig = "blank", 
                              title = "Biosphere 2 Ocean Water Quality Correlations\n
                              Significant Correlations Shown (PValue < 0.05)")
# Save Plot
ggsave(filename = "HachYSI-Correlogram-Significant.pdf", 
       plot = corrPlot_signif,
       path = "Figures/HachYSI/02_Paper",
       width = 15, height = 15)


```

