---
title: "Nutrients Figures: Correlations"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---
# Nutrient Correlations
## Import Libraries
```{r import libraries}
library(tidyverse)
library(Hmisc)
library(corrplot)
library(PerformanceAnalytics)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999)
```

## Import Data
```{r import data}
df <- read_csv("Data/Clean/Nutrients/02_QualityControl/01-Nutrients-Data-Clean-QC.csv")
```


## Correlation Plots
### All
#```{r cor plots}
# # Correlogram
# { # open pdf graphics driver
#   pdf(file = "Figures/Nutrients/04_Correlations/01-Nutrients-Correlogram.pdf")
#   # make correlation plot
#   corrplot(cor_mat, type = "upper", order = "hclust", 
#            tl.col = "black", tl.srt = 45, mar = c(0, 0, 5, 0),
#            title = "Biosphere 2 Ocean Water Quality Correlations")
#   # close graphics driver
#   dev.off()
# }
# 
# # Correlogram with Significance
# cor_mat_stats$P[is.na(cor_mat_stats$P)] <- 1 #turn NAs into 1's (insignificant)
# { # open pdf graphics driver
#   pdf(file = "Figures/Nutrients/04_Correlations/02-Nutrients-Correlogram-PValues.pdf")
#   corrplot(cor_mat_stats$r, type="upper", order="hclust", 
#            tl.col = "black", tl.srt = 45, mar = c(0, 1, 5, 0),
#            p.mat = cor_mat_stats$P, sig.level = 0.05, insig = "blank",
#            title = "Biosphere 2 Ocean Water Quality Significant Correlations \n
#            P-Value < 0.05")
#   # close graphics driver
#   dev.off()
# }
# 
# # Heat Map
# col<- colorRampPalette(c("blue", "white", "red"))(20) #get colors
# { # open pdf graphics driver
#   pdf(file = "Figures/Nutrients/04_Correlations/03-Nutrients-HeatMap.pdf")
#   heatmap(x = cor_mat, col = col, symm = TRUE,
#           title = "Biosphere 2 Ocean Water Quality Heat Map", 
#           margins = c(12,12))
#   # close graphics driver
#   dev.off()
# }
# 
# # Scatter Plots -- large files
# dfScatter <- df %>%
#   select(-c(pH_mV, nlf_conductivity_uScm, sp_conductivity_uScm, do_mgL,
#             do_saturated_percent, chlorophyll_ugL, total_algae_cellsL))
# { # open pdf graphics driver
#   pdf(file = "Figures/Nutrients/04_Correlations/04-Nutrients-CorrelationChart.pdf")
#   chart.Correlation(dfScatter, histogram=TRUE, pch=19)
#   # close graphics driver
#   dev.off()
#   }

#```

### Ocean
```{r ocean correlations}
df_ocean <- df %>%
  filter(Location == "Ocean") %>%
  select(-Date, -Location, -Ammonia)

# create nested list of matrices: p-values, n, r values
cor_mat_ocean <- rcorr(as.matrix(df_ocean))

cor_mat_ocean_pvals <- cor_mat_ocean$P %>%
  round(2)

cor_mat_ocean_coefs <- cor_mat_ocean$r %>%
  round(2)

# full flattened correlation matrix
cor_mat_stats_flat_ocean <- flattenCorrMatrix(cor_mat_ocean$r, cor_mat_ocean$P) %>%
  mutate(across(3:4, ~ round(.x, 2)))

# Correlogram
{ # open pdf graphics driver
  pdf(file = "Figures/Nutrients/04_Correlations/Ocean/Nutrients-Correlations-Ocean-Correlogram.pdf",
      width = 13, height = 10)
  # make correlation plot
  corrplot(cor_mat_ocean$r, method = "number", outline = TRUE, type = "full", diag = TRUE,
           order = "original", 
           tl.col = "black", tl.srt = 45, mar = c(0, 0, 3, 0),
           title = "Biosphere 2 Ocean Nutrient Water Quality Correlations")
  # close graphics driver
  dev.off()
}

# # Correlogram with Significance
# cor_mat_stats_ocean$P[is.na(cor_mat_stats_ocean$P)] <- 1 #turn NAs into 1's (insignificant) -- only NA values are on the diagonal (temp_f compared to temp_f etc)
# { # open pdf graphics driver
#   pdf(file = "Figures/Nutrients/04_Correlations/Ocean/Nutrients-Correlations-Ocean-Correlogram-PValues.pdf",
#       width = 13, height = 10)
#   corrplot(cor_mat_stats_ocean$r, method = "shade", type="full", order="original", 
#            diag = TRUE, 
#            tl.col = "black", tl.srt = 45, mar = c(0, 0, 4, 0),
#            p.mat = cor_mat_stats_ocean$P, sig.level = 0.05, insig = "p-value",
#            title = "Biosphere 2 Ocean Nutrient Water Quality Significant Correlations \n
#            P-Value < 0.05")
#   # close graphics driver
#   dev.off()
# }

```


### Mangroves

### Raceway 1

### Raceway 2