---
title: "Hach and YSI Figures for Paper"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---

```{r import-libraries}
library(tidyverse)
library(lubridate)
#library(Hmisc)
library(corrplot)
# library(ggcorrplot)
source("Code/Functions/CorrelationFunction.R")
options(scipen = 999) 
```

```{r import-data}
# time series data
dfTS <- read_csv("Data/Clean/HachYSI/01_DataWrangling/05-HachYSI-Data-All.csv") %>%
  select(-pH_Hach) %>% #take out pH data from Hach
  rename(pH = `pH (YSI)`, #rename pH data from YSI to just pH
         `Nitrate (mg/L)` = `Nitrate, Mid-Range (mg/L)`) %>% # rename Nitrate MR to just Nitrate
  mutate(`Temperature (ºC)` = ifelse(Date >= "2021-01-01" & Date < "2022-01-02" & `Temperature (ºC)` > 25.5, NA, `Temperature (ºC)`))

# correlation data
## pvalue matrix
# matPval <- read_csv("Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-Pvalues.csv") %>%
#   rename(`Nitrate (mg/L)` = `Nitrate, Mid-Range (mg/L)`)
# ## rvalue matrix
# matRval <- read_csv("Data/Clean/HachYSI/02_Correlations/HachYSI-CorrelationMatrix-RValues.csv") %>%
#   rename(`Nitrate (mg/L)` = `Nitrate, Mid-Range (mg/L)`)

```

# B2O History 2011-2024
```{r history}
# history plot 
# 1x3: Temp C, Salinity (PSU), pH; 2011-2024
plotHistory <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  # keep just date, temperature celcius, salinity psu, and pH columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH) %>%
  pivot_longer(cols = `Temperature (ºC)`:pH,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)","Salinity (PSU)","pH")))) %>%
  ggplot(aes(x = Date,
             y = var_value)) +
  facet_wrap(~var_name,
             ncol = 1,
             scales = "free_y",
             strip.position = "left", 
             labeller = as_labeller(c(`Temperature (ºC)` = "Temperature (ºC)", 
                                      `Salinity (PSU)` = "Salinity (PSU)",
                                      pH = "pH"))) +
  geom_point(size = 0.25) +
  scale_x_date(date_breaks = "year",
               date_labels = "%Y") +
  ylab(NULL) +
  xlab(NULL) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.background = element_blank(), 
        strip.placement = "outside")
  
plotHistory

# Save Plot
ggsave(filename = "HachYSI-1x3HistoryPlot.png",
       plot = plotHistory,
       path = "Figures/HachYSI/02_Paper")


```

# Environmental Variability 2021-2024
```{r current}
# environmental variability plot 
# 1x3: Temp C, Salinity (PSU), pH; 2021-2024
plotCurrent <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  filter(Date >= "2021-01-01") %>%
  # keep just date, temperature celcius, salinity psu, and pH columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH) %>%
  pivot_longer(cols = `Temperature (ºC)`:pH,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)","Salinity (PSU)", "pH")))) %>%
  ggplot(aes(x = Date,
             y = var_value)) +
  facet_wrap(~var_name,
             ncol = 1,
             scales = "free_y",
             strip.position = "left", 
             labeller = as_labeller(c(`Temperature (ºC)` = "Temperature (ºC)", 
                                      `Salinity (PSU)` = "Salinity (PSU)",
                                      pH = "pH"))) +
  geom_point(size = 0.25) +
  scale_x_date(date_breaks = "year",
               date_labels = "%Y") +
  ylab(NULL) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.background = element_blank(), 
        strip.placement = "outside")
  
plotCurrent

# Save Plot
# ggsave(filename = "HachYSI-1x3CurrentPlot.png",
#        plot = plotCurrent,
#        path = "Figures/HachYSI/02_Paper",
#        width = 6,
#        height = 4)

```

# Nutrients and Water Quailty Time Series 2020-2024
```{r nutrients-water-qual-timeseries}
# nutrients and water quality time series plot 
# Temp, Salinity, pH, Alaklinity Nitrate, Phosphate, Silica, Iron, DO; 2021-2024 
dfNutWatQual_reg <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Daily") %>%
  filter(Date >= "2021-01-01")%>%
  filter(`Dissolved Oxygen (mg/L)` < 7.0) %>%
  # keep just date, alkalinity, nitrate mr, iron, and silica columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH, `Alkalinity (mg/L CaCO3)`, `Nitrate (mg/L)`, `Phosphate (mg/L)`, `Silica (mg/L)`, `Iron (mg/L)`, `Dissolved Oxygen (mg/L)`) %>%
  pivot_longer(cols = `Temperature (ºC)`:`Dissolved Oxygen (mg/L)`,
               names_to = "var_name",
               values_to = "var_value") %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)"))))

dfNutWatQual_naomit <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Monthly") %>%
  filter(Date >= "2021-01-01") %>%
  filter(`Dissolved Oxygen (mg/L)` < 7.0) %>%
  # keep just date, alkalinity, nitrate mr, iron, and silica columns
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH, `Alkalinity (mg/L CaCO3)`, `Nitrate (mg/L)`, `Phosphate (mg/L)`, `Silica (mg/L)`, `Iron (mg/L)`, `Dissolved Oxygen (mg/L)`) %>%
  pivot_longer(cols = `Temperature (ºC)`:`Dissolved Oxygen (mg/L)`,
               names_to = "var_name",
               values_to = "var_value") %>%
  na.omit() %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)"))))

plotNutWatQual_ts <- 
    ggplot(data = dfNutWatQual_reg,
           aes(x = Date,
               y = var_value)) +
    facet_wrap(~var_name,
               ncol = 2,
               scales = "free_y",
               strip.position = "left", 
               labeller = as_labeller(c(`Temperature (ºC)` = "Temperature (ºC)",
                                        `Salinity (PSU)` = "Salinity (PSU)",
                                        pH = "pH", 
                                        `Alkalinity (mg/L CaCO3)` = "Alkalinity (mg/L CaCO3)",
                                        `Nitrate (mg/L)` = "Nitrate (mg/L)",
                                        `Phosphate (mg/L)` = "Phosphate (mg/L)", 
                                        `Silica (mg/L)` = "Silica (mg/L)",
                                        `Iron (mg/L)` = "Iron (mg/L)",
                                        `Dissolved Oxygen (mg/L)` = "Dissolved Oxygen (mg/L)"))) +
    geom_point(color = "lightgray",
               alpha = 0.4) +
    geom_line(data = dfNutWatQual_naomit,
              aes(x = Date,
               y = var_value)) +
    scale_x_date(date_breaks = "year",
                 date_labels = "%Y") +
    ylab(NULL) +
    xlab(NULL) +
    theme_bw() + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          axis.line = element_line(colour = "black"),
          strip.background = element_blank(), 
          strip.placement = "outside") 

plotNutWatQual_ts

# Save Plot
# ggsave(filename = "HachYSI-NutWatQualPlot-TimeSeries.png",
#        plot = plotNutWatQual_ts,
#        path = "Figures/HachYSI/02_Paper",
#        height = 8)


```

# Seasonal Variation 2021-2024
```{r nutrients-water-qual-climatology}
# nutrients and water quality time series plot 
# Temp, Salinity, pH, Alaklinity Nitrate, Phosphate, Silica, Iron, DO; 2021-2024 
dfNutWatQual_s <- dfTS %>%
  # use Daily time interval
  filter(`Time Interval` == "Monthly") %>%
  filter(Date >= "2021-01-01") %>%
  filter(`Dissolved Oxygen (mg/L)` < 7.0) %>%
  # keep just columns that will be plotted
  select(Date, `Temperature (ºC)`, `Salinity (PSU)`, pH, `Alkalinity (mg/L CaCO3)`, `Nitrate (mg/L)`, `Phosphate (mg/L)`, `Silica (mg/L)`, `Iron (mg/L)`, `Dissolved Oxygen (mg/L)`) %>%
  # pivot dataframe longer bc ggplot likes that better
  pivot_longer(cols = `Temperature (ºC)`:`Dissolved Oxygen (mg/L)`,
               names_to = "var_name",
               values_to = "var_value") %>%
  # add month number (jan = 1, feb = 2, etc)
  mutate(month = month(Date, label = FALSE)) %>%
  group_by(month, var_name) %>%
  # use reframe instead of summarise bc it'll return more cols and rows 
  reframe(min = min(var_value, na.rm = TRUE),
          max = max(var_value, na.rm = TRUE),
          mean = mean(var_value, na.rm = TRUE),
          q1 = quantile(var_value, 0.25, na.rm = TRUE),
          q2 = quantile(var_value, 0.75, na.rm = TRUE)) %>%
  mutate(Date = as.Date(paste(2021, month, 01, sep = "-"))) %>%
  mutate(across(var_name, ~factor(., levels=c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)")))) 

# plot 
plotNutWatQual_s <- dfNutWatQual_s %>%
  ggplot(aes(x = as.Date(yday(Date), "2021-01-01"),
             y = mean)) +
  facet_wrap(~var_name,
             ncol = 2,
             scales = "free_y",
             strip.position = "left", 
             labeller = as_labeller(c(`Temperature (ºC)` = "Temperature (ºC)",
                                      `Salinity (PSU)` = "Salinity (PSU)",
                                      pH = "pH", 
                                      `Alkalinity (mg/L CaCO3)` = "Alkalinity (mg/L CaCO3)",
                                      `Nitrate (mg/L)` = "Nitrate (mg/L)",
                                      `Phosphate (mg/L)` = "Phosphate (mg/L)", 
                                      `Silica (mg/L)` = "Silica (mg/L)",
                                      `Iron (mg/L)` = "Iron (mg/L)",
                                      `Dissolved Oxygen (mg/L)` = "Dissolved Oxygen (mg/L)"))) +
  geom_line() +
  geom_ribbon(aes(ymin = q1,
                  ymax = q2), 
              color = "lightgray",
              alpha = 0.3) +
  scale_x_date(date_breaks = "month",
               date_labels = "%B") +
  scale_y_continuous(breaks = waiver(), n.breaks = 6) +
  ylab(NULL) +
  xlab(NULL) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.background = element_blank(), 
        strip.placement = "outside") 
  
plotNutWatQual_s

# Save Plot
ggsave(filename = "HachYSI-NutWatQualPlot-Climatology.png",
       plot = plotNutWatQual_s,
       path = "Figures/HachYSI/02_Paper",
       height = 8)


```



```{r nutrients-water-qual-correlation}
# Correlation Matrix, Significant; 2021-2024 
# change row names of dataframes to be the column names
row_names <- colnames(matPval)
rownames(matPval) <- row_names
rownames(matRval) <- row_names

matPval <- matPval[c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)"), c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)")]

matRval <- matRval[c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)"), c("Temperature (ºC)", "Salinity (PSU)", "pH", "Alkalinity (mg/L CaCO3)", "Nitrate (mg/L)", "Phosphate (mg/L)", "Silica (mg/L)", "Iron (mg/L)", "Dissolved Oxygen (mg/L)")]

row_names <- colnames(matPval)
rownames(matPval) <- row_names
rownames(matRval) <- row_names

# turn both dataframes into matrices
matRval <- as.matrix(matRval)
matPval <- as.matrix(matPval)

# turn NAs into insignificant values
matPval[is.na(matPval)] <- 1.00 
matRval[is.na(matRval)] <- 0.00

# Correlogram with Significance
corrPlot_signif <- ggcorrplot(matRval, 
                              p.mat = matPval,
                              outline.color = "white", 
                              ggtheme = ggplot2::theme_gray(), 
                              colors = c("#6D9EC1", "white", "#E46726"), 
                              lab = TRUE,
                              insig = "blank")
corrPlot_signif

# Save Plot
ggsave(filename = "HachYSI-Correlogram-Significant.pdf",
       plot = corrPlot_signif,
       path = "Figures/HachYSI/02_Paper",
       width = 7, height = 7)

```

