---
title: "YSI Figures Post-QC"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

## Import Libraries
```{r Libraries}
library(tidyverse)
library(lubridate)
```

# Import Data
```{r import data}
# Data after QC -- values outside of 2 sigma away from mean of every month for every variable were turned into NA values
df <- read_csv("Data/Clean/YSI/02_QualityControl/01-YSI-Data-QC.csv")

# Data after QC and Cutoff values implemented
dfCutoff <- read_csv("Data/Clean/YSI/02_QualityControl/02-YSI-Data-QCCutoff.csv")
```

# Data Formatting
```{r data formatting}
# pivot df longer for easier all-variable plotting
dfPivot <- df %>%
  pivot_longer(cols = `Temperature (ºF)`:`Total Dissolved Solids (mg/L)`,
               names_to = "variable",
               values_to = "variable_value")

# pivot dfCut longer for easier all-variable plotting
dfCutPivot <- dfCutoff %>%
  pivot_longer(cols = `Temperature (ºF)`:`Total Dissolved Solids (mg/L)`,
               names_to = "variable",
               values_to = "variable_value")

# character vector of variable names as they appear in the dataframes
variable_names <- unique(dfPivot$variable)

# character vector of variable names as they should be written on a graph
variable_text <- colnames(df)
variable_text <- variable_text[! variable_text %in% c("Date", "Time")]


# character vector of file names for plots
file_names <- c("TempFPlot", "TempCPlot", "pHPlot", "pHmVPlot", "SalinityPlot",
                "ConductivityPlot", "NlfConductivityPlot", "SpConductivityPlot",
                "DomglPlot", "DoSatPlot", "DoLocalPlot", "OrpPlot", "ChlorophyllRfuPlot",
                "ChlorophylluglPlot", "TotalAlgaeRfuPlot", "TotalAlgaeCellsLPlot",
                "TotalDissolvedSolidsPlot")

```

# Plotting
## Compare Initial Standard Deviation QC to QC with Cutoffs Implemented
### All Variables on Same Line Graph
```{r Initial Vs Cutoffs Line Graphs, Facet Wrapped}
# line graph of every variable (facet wrapped) after initial standard deviation QC
AllVariablePlot_PostQC <- dfPivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-PostQC.pdf", plot = AllVariablePlot_PostQC, 
       path = "Figures/YSI/02_PostQC", height = 12, width = 10)


# line graph of every variable (facet wrapped) after initial QC and Cutoffs
AllVariablePlot_PostQCCutoff <- dfCutPivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Post-QC and Cutoffs: Data Outside 2-Sigma from Mean and Cutoff Values have been Removed\npH < 7.5; Salinity (PSU) < 21; Temp (ºC) < 20 and > 28")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-PostQCCutoff.pdf", 
       plot = AllVariablePlot_PostQCCutoff, 
       path = "Figures/YSI/02_PostQC", height = 12, width = 10)

```

## After Cutoff Values Were Implemented
### Individual Graphs
#### Line Graphs
##### Time Series
```{r Line Graphs: Time Series}
# individual line graphs of each variable after cutoffs have been implemented for pH, Salinity, and Temp C

# list to save plots from loop into
plotList_postqc <- list()
# loop through each variable, plot, save
for (i in 1:length(variable_names)) {
  plotList_postqc[[i]] <- dfCutPivot %>%
    filter(variable == variable_names[i]) %>%
    filter(ifelse(variable == "Conductivity, Non-Linear Function (µS/cm)" |
                    variable == "pH (mV)" |
                    variable == "Conductivity, Specific (µS/cm)" |
                    variable == "Dissolved Oxygen (mg/L)" |
                    variable == "Dissolved Oxygen, Local (%)" |
                    variable == "Chlorophyll (RFU)" |
                    variable == "Total Dissolved Solids (mg/L)", 
                  Date >= "2021-01-01",
                  Date == Date)) %>%
    filter(ifelse(variable == "Dissolved Oxygen, Saturated (%)" |
                    variable == "Chlorophyll (µg/L)" |
                    variable == "Total Algae (RFU)" |
                    variable == "Total Algae (cells/L)", 
                  Date >= "2018-01-01", 
                  Date == Date)) %>%
    ggplot(aes(x = Date, 
               y = variable_value)) +
    geom_line() +
    scale_x_date(date_breaks = "1 year",
                 date_labels = "%b %Y") +
    theme_bw() + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(#title = paste("B2O", variable_text[i], "from 2011-2023"),
         title = variable_text[i],
         #subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
         x = "Date",
         y = variable_text[i])
  
  print(plotList_postqc[[i]])
  
  # Save plot
  ggsave(plot = plotList_postqc[[i]],
         #filename = paste(file_names[i],"-PostQC-Line-TimeSeries.pdf", sep = ""),
         #path = "Figures/YSI/02_PostQC/LineGraphs/TimeSeries")
         filename = paste(file_names[i],"-B2SymposiumPoster-Line-TimeSeries.pdf", sep = ""),
         path = "Figures/YSI/05_B2SymposiumPoster/LineGraphs/TimeSeries")
}

```
##### Seasonal
```{r Line Graphs: Seasonal}
# loop through each variable, plot line graph showing data for each year stacked on same plot, save plot
# list to save plots from loop into
plotList_postqc <- list()
# loop through each variable, plot, save
for (i in 1:length(variable_names)) {
  plotList_postqc[[i]] <- dfCutPivot %>%
    filter(variable == variable_names[i]) %>%
    filter(ifelse(variable == "Conductivity, Non-Linear Function (µS/cm)" |
                    variable == "pH (mV)" |
                    variable == "Conductivity, Specific (µS/cm)" |
                    variable == "Dissolved Oxygen (mg/L)" |
                    variable == "Dissolved Oxygen, Local (%)" |
                    variable == "Chlorophyll (RFU)" |
                    variable == "Total Dissolved Solids (mg/L)", 
                  Date >= "2021-01-01",
                  Date == Date)) %>%
    filter(ifelse(variable == "Dissolved Oxygen, Saturated (%)" |
                    variable == "Chlorophyll (µg/L)" |
                    variable == "Total Algae (RFU)" |
                    variable == "Total Algae (cells/L)", 
                  Date >= "2018-01-01", 
                  Date == Date)) %>%
    ggplot(aes(x = as.Date(yday(Date), "2021-01-01"), #use each day of the year as the x axis data
               color = factor(year(Date)), #plot data from each year separately as its own color
               y = variable_value)) + #use variable values as y axis data
    geom_line() +
    scale_x_date(date_breaks = "months", date_labels = "%b") +
    theme_bw() + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(#title = paste("B2O", variable_text[i], "from 2011-2023"),
         #subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
         title = variable_text[i],
         x = "Date",
         y = variable_text[i],
         color = "Year")
  
  print(plotList_postqc[[i]])
  
  # Save plot
  ggsave(plot = plotList_postqc[[i]],
         # filename = paste(file_names[i],"-PostQC-Line-Seasonal.pdf", sep = ""),
         # path = "Figures/YSI/02_PostQC/LineGraphs/Seasonal")
         filename = paste(file_names[i],"-B2SymposiumPoster-Line-Seasonal.pdf", sep = ""),
         path = "Figures/YSI/05_B2SymposiumPoster/LineGraphs/Seasonal")
}

```
####Loess Graphs
##### Time Series
```{r Loess Graphs: Time Series}
# individual line graphs of each variable after cutoffs have been implemented for pH, Salinity, and Temp C

# list to save plots from loop into
plotList_postqc <- list()
# loop through each variable, plot, save
for (i in 1:length(variable_names)) {
  plotList_postqc[[i]] <- dfCutPivot %>%
    filter(variable == variable_names[i]) %>%
    filter(ifelse(variable == "Conductivity, Non-Linear Function (µS/cm)" |
                    variable == "pH (mV)" |
                    variable == "Conductivity, Specific (µS/cm)" |
                    variable == "Dissolved Oxygen (mg/L)" |
                    variable == "Dissolved Oxygen, Local (%)" |
                    variable == "Chlorophyll (RFU)" |
                    variable == "Total Dissolved Solids (mg/L)", 
                  Date >= "2021-01-01",
                  Date == Date)) %>%
    filter(ifelse(variable == "Dissolved Oxygen, Saturated (%)" |
                    variable == "Chlorophyll (µg/L)" |
                    variable == "Total Algae (RFU)" |
                    variable == "Total Algae (cells/L)", 
                  Date >= "2018-01-01", 
                  Date == Date)) %>%
    ggplot(aes(x = Date, 
               y = variable_value)) +
    geom_line() +
    geom_smooth() +
    scale_x_date(date_breaks = "1 year",
                 date_labels = "%b %Y") +
    theme_bw() + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(#title = paste("B2O", variable_text[i], "from 2011-2023"),
         #subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed",
      title = variable_text[i],   
      x = "Date",
         y = variable_text[i])
  
  print(plotList_postqc[[i]])
  
  # Save plot
  ggsave(plot = plotList_postqc[[i]],
         # filename = paste(file_names[i],"-PostQC-Loess-TimeSeries.pdf", sep = ""),
         # path = "Figures/YSI/02_PostQC/LoessGraphs/TimeSeries")
         filename = paste(file_names[i],"-B2SymposiumPoster-Loess-TimeSeries.pdf", sep = ""),
         path = "Figures/YSI/05_B2SymposiumPoster/LoessGraphs/TimeSeries")
         
}
```
##### Seasonal
```{r Loess Graphs: Seasonal}
# loop through each variable, plot line graph showing data for each year stacked on same plot, save plot
# list to save plots from loop into
plotList_postqc <- list()
# loop through each variable, plot, save
for (i in 1:length(variable_names)) {
  plotList_postqc[[i]] <- dfCutPivot %>%
    filter(variable == variable_names[i]) %>%
    filter(ifelse(variable == "Conductivity, Non-Linear Function (µS/cm)" |
                    variable == "pH (mV)" |
                    variable == "Conductivity, Specific (µS/cm)" |
                    variable == "Dissolved Oxygen (mg/L)" |
                    variable == "Dissolved Oxygen, Local (%)" |
                    variable == "Chlorophyll (RFU)" |
                    variable == "Total Dissolved Solids (mg/L)", 
                  Date >= "2021-01-01",
                  Date == Date)) %>%
    filter(ifelse(variable == "Dissolved Oxygen, Saturated (%)" |
                    variable == "Chlorophyll (µg/L)" |
                    variable == "Total Algae (RFU)" |
                    variable == "Total Algae (cells/L)", 
                  Date >= "2018-01-01", 
                  Date == Date)) %>%
    ggplot(aes(x = as.Date(yday(Date), "2021-01-01"), #use each day of the year as the x axis data
               color = factor(year(Date)), #plot data from each year separately as its own color
               y = variable_value)) + #use variable values as y axis data
    geom_smooth() +
    scale_x_date(date_breaks = "months", date_labels = "%b") +
    theme_bw() + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(#title = paste("B2O", variable_text[i], "from 2011-2023"),
         #subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
      title = variable_text[i],      
      x = "Date",
         y = variable_text[i],
      color = "Year") 
  
  print(plotList_postqc[[i]])
  
  # Save plot
  ggsave(plot = plotList_postqc[[i]],
         # filename = paste(file_names[i],"-PostQC-Loess-Seasonal.pdf", sep = ""),
         # path = "Figures/YSI/02_PostQC/LoessGraphs/Seasonal")
         filename = paste(file_names[i],"-B2SymposiumPoster-Loess-Seasonal.pdf", sep = ""),
         path = "Figures/YSI/05_B2SymposiumPoster/LoessGraphs/Seasonal")
}

```

