---
title: "YSI Figures: Descriptive Statistics"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

## Import Libraries
```{r Libraries}
library(tidyverse)
library(lubridate)
```

## Import Data
```{r import data}
# qc cutoff data
df <- read_csv("Data/Clean/YSI/02_QualityControl/02-YSI-Data-QCCutoff.csv")

# whole time series
dfWhole <- read_csv("Data/Clean/YSI/03_DescriptiveStatistics/01-YSI-SeriesDescriptiveStats-Whole.csv")

# yearly
dfYear <- read_csv("Data/Clean/YSI/03_DescriptiveStatistics/02-YSI-DescriptiveStats-Yearly.csv")

# monthly
dfMonth <- read_csv("Data/Clean/YSI/03_DescriptiveStatistics/03-YSI-DescriptiveStats-Monthly.csv")

# daily
dfDay <- read_csv("Data/Clean/YSI/03_DescriptiveStatistics/04-YSI-DescriptiveStats-Daily.csv")
```

## Data Formatting
```{r data formatting}
# character vector of variable names as they appear in the dataframes
variable_names <- c(dfWhole$variable)

# character vector of variable names as they should be written on a graph
variable_text <- c("Temperature (ºF)", "Temperature (ºC)", "pH", "pH (mV)",
                   "Salinity (PSU)", "Conductivity (µS/cm)", 
                   "NLF Conductivity (µS/cm", "Specific Conductivity (µS/cm)",
                   "Dissolved Oxygen (mg/L)", "Dissolved Oxygen, Saturated (%)",
                   "Dissolved Oxygen, Local (%)", "ORP (mV)", "Chlorophyll (RFU)",
                   "Chlorophyll (µg/L)", "Total Algae (RFU)", "Total Algae (cells/L)",
                   "Total Dissolved Solids (mg/L)")


# character vector of file names for plots
file_names <- c("TempFPlot", "TempCPlot", "pHPlot", "pHmVPlot", "SalinityPlot",
                "ConductivityPlot", "NlfConductivityPlot", "SpConductivityPlot",
                "DomglPlot", "DoSatPlot", "DoLocalPlot", "OrpPlot", "ChlorophyllRfuPlot",
                "ChlorophylluglPlot", "TotalAlgaeRfuPlot", "TotalAlgaeCellsLPlot",
                "TotalDissolvedSolidsPlot")



```


# Line Plots
## Yearly
```{r yearly plots}
# whole time series #not sure if want to plot this yet bc it's just one value instead of multiple values spanning  time intervals

# plots of mean, median, std, iqr for each year over course of time series

# list for plots to populate from loop
plotList_year <- list()

for (i in 1:length(variable_names)) {
plotList_year[[i]] <- dfYear %>%
  filter(variable == variable_names[i]) %>%
  ggplot((aes(x = year))) +
  geom_ribbon(aes(y = mean,
                  ymin = mean - std,
                  ymax = mean + std,
                  fill = "Standard Deviation"), 
              alpha = 0.2,
              show.legend = TRUE) +
  geom_ribbon(aes(y = median,
                  ymin = Q1,
                  ymax = Q3,
                  fill = "Interquartile Range"), 
              alpha = 0.2,
              show.legend = TRUE) +
  geom_line(aes(y = mean, color = "Mean"), 
            show.legend = TRUE) +
  geom_line(aes(y = median, color = "Median"), 
            show.legend = TRUE) +
  scale_x_continuous(n.breaks = length(unique(dfYear$year)))+
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("blue", "red")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = paste("B2O", variable_text[i], "Yearly Statistics from 2011-2023"),
       x = "Date",
       y = variable_text[i],
       fill = "",
       color = "")
print(plotList_year[[i]])
# Save plot
ggsave(plot = plotList_year[[i]],
       filename = paste(file_names[i],"-Year-DescriptiveStats.pdf", sep = ""),
       path = "Figures/YSI/03_DescriptiveStatistics/Yearly")
}

```

## Monthly
### Seasonal Cycle
```{r monthly plots}
# line plots for each parameter showing monthly means with each year stacked on the same plot to emphasize seasonal cycles

plotList_month <- list()

for (i in 1:length(variable_names)) {
  plotList_month[[i]] <- dfMonth %>%
    mutate(date = paste(year, month, 01, sep = "-"),
           date = as.Date(strptime(date, format = "%Y-%b-%d"))) %>%
    filter(variable == variable_names[i],
           date >= "2011-01-01" & date < "2023-01-01") %>%
    ggplot(aes(x = as.Date(yday(date), "2021-01-01"),
               color = factor(year(date)),
               y = median)) +
    geom_line() +
    scale_x_date(date_breaks = "months", date_labels = "%b")+
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(title = paste("B2O", variable_text[i], "Monthly Median from 2011-2023"), 
         x = "Date",
         y = variable_text[i], 
         color = "Year")
  print(plotList_month[[i]])
  # Save plot
  ggsave(plot = plotList_month[[i]],
         filename = paste(file_names[i],"-DescriptiveStats-Month-Seasonal.pdf", sep = ""),
         path = "Figures/YSI/03_DescriptiveStatistics/Monthly/Seasonal")
}


```

### Total Interval
```{r}
plotList_month <- list()

for (i in 1:length(variable_names)) {
  plotList_month[[i]] <- dfMonth %>%
    mutate(date = paste(year, month, 01, sep = "-"),
           date = as.Date(strptime(date, format = "%Y-%b-%d"))) %>%
    filter(variable == variable_names[i],
           year >= "2011" & year < "2023") %>%
    ggplot(aes(x = date,
               y = median)) +
    geom_line() +
    scale_x_date(date_breaks = "years", date_labels = "%Y")+
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(title = paste("B2O Monthly Median", variable_text[i], "from 2011-2023"), 
         x = "Date",
         y = variable_text[i])
  print(plotList_month[[i]])
  # Save plot
  ggsave(plot = plotList_month[[i]],
         filename = paste(file_names[i],"-DescriptiveStats-Month-TimeSeries.pdf", sep = ""),
         path = "Figures/YSI/03_DescriptiveStatistics/Monthly/TimeSeries")
}
```



## Daily
```{r Daily Plots}
# line plots showing daily changes each year
plotList_day <- list()

for (i in 1:length(variable_names)) {
  plotList_day[[i]] <- dfDay %>%
    mutate(date = paste(year, month, day, sep = "-"),
           date = as.Date(strptime(date, format = "%Y-%b-%d"))) %>%
    filter(variable == variable_names[i],
           date >= "2011-01-01" & date < "2023-01-01",) %>%
    ggplot(aes(x = as.Date(yday(date), "2021-01-01"),
               y = mean,
               color = factor(year(date)))) +
    geom_line() +
    # geom_line(aes(y = median, color = "Median"), show.legend = TRUE) +
    scale_x_date(date_breaks = "months", date_labels = "%b")+
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
    theme(strip.background = element_rect(fill = "white"))+
    labs(title = paste("B2O", variable_text[i], "Daily Statistics from 2011-2023"), 
         x = "Date",
         y = variable_text[i], 
         color = "Year")
  print(plotList_day[[i]])
  # Save plot
  ggsave(plot = plotList_day[[i]],
         filename = paste(file_names[i],"-Day-DescriptiveStats.pdf", sep = ""),
         path = "Figures/Figures_YSI/03-DescriptiveStatisticsPlots/DailyStatistics")
}

# plot daily means by month of each year -- use only if indicated by Diane
# dfDay %>%
#     mutate(date = paste(year, month, day, sep = "-"),
#            date = as.Date(strptime(date, format = "%Y-%b-%d"))) %>%
#     filter(variable == "temp_c",
#            date >= "2011-01-01" & date < "2023-01-01",
#            month == "July") %>%
#     ggplot(aes(x = as.Date(mday(date), "2021-07-01"),
#                y = mean,
#                color = factor(year(date)))) +
#     geom_line() +
#   #geom_line(aes(y = median, color = "Median"), show.legend = TRUE) +
#     scale_x_date(date_breaks = "weeks", date_labels = "%b-%d")+
#     theme_bw() +
#     theme(panel.grid.major = element_blank(),
#           panel.grid.minor = element_blank(),
#           panel.background = element_blank(),
#           axis.line = element_line(colour = "black"))+
#     theme(axis.text.x = element_text(angle = 45, hjust = 1),
#           plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
#     theme(strip.background = element_rect(fill = "white"))+
#     labs(title = "B2O Temperature (ºC) Daily Means from July 2011-2022", 
#          x = "Date",
#          y = "Temperature (ºC)", 
#          color = "")


```