---
title: "Ocean Data Quality Control"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---
# Import Libraries
```{r Import Libraries}
library(tidyverse)
library(lubridate)
library(here)
# source("./QCFunction.R")

# turns scientific notation off
options(scipen = 999)
```


# Data Quality Control
## Import Raw Data
```{r Import Data}
# uses csv file created in OceanDataWrangling.Rmd. do not need to re-run that file to use this csv
OceanWaterQualityFrame <- read_csv("Data/CleanData/CleanData_YSI/01_DataWrangling/OceanWaterQualityFrame.csv")

```
## Plot Pre-QC Data
```{r Visualize Data Before QC Performed}
OceanWaterQualityFramePivot <- OceanWaterQualityFrame %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))

AllVariablePlotPreQC <- OceanWaterQualityFramePivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Nutrient Value")

AllVariablePlotPreQC

```

## Quality Control Data
### QC Function
```{r QC Function}
# The following code defines a function to identify data points outside input standard deviations from the mean or median for each nutrient at each location and replaces the identified outliers with NA values

# empty dataframe with same column names and number of rows as OceanWaterQualityFrame
dfQC <- data.frame(matrix(ncol = 2, nrow = nrow(OceanWaterQualityFrame)))
colnames(dfQC) <- c("date", "time")
# filling in date and time columns with same values from OceanWaterQualityFrame
dfQC <- dfQC %>%
  mutate(date = OceanWaterQualityFrame$date,
         time = OceanWaterQualityFrame$time)
# getting list of column names, excluding "date" and "time" 
var_names <- colnames(OceanWaterQualityFrame)
var_names <- var_names[! var_names %in% c("date", "time")]

# loopin time
for (v in var_names) {
  # create frame with just date, time, and var columns
  var <- OceanWaterQualityFrame[[v]]
  
  dfVar <- OceanWaterQualityFrame[, c("date", "time")]
  dfVar <- cbind(dfVar, var)
  
  dfVar <- dfVar %>%
    mutate(date = format(as.Date(date), "%Y-%m"),#mutate date column so it's just year and month
           stat = NA) %>%
    group_by(date) %>%
    mutate(sd_monthly = sd(as.numeric(var), na.rm = TRUE),
           mean_monthly = mean(as.numeric(var), na.rm = TRUE),
           mad_monthly = mad(as.numeric(var), na.rm = TRUE))
  
  # create vector of unique dates from dfVar. Will give just the unique year/month combos
  unique_dates <- unique(dfVar$date)

  for (d in unique_dates) {
    # filter dfVar by month and use only unique values
    dfVarNormal <- dfVar %>%
      filter(date == d) %>%
      unique()
    
    # run shapiro test on var values if there are more than 3 unique values. 
    # p-value will be saved in shapiro_value if above is true, otherwise, sample will be considered non-normal, and shapiro_value will be saved as 0 
    shapiro_value <- NA
    if (length(unique(dfVarNormal$var)) <= 3) {
      shapiro_value <- 0
    } else {
      shapiro_value <- shapiro.test(as.numeric(dfVarNormal$var))$p.value
    }
    
    # if shapiro_value is not significant, then make stat values where date == d be equal to "mean", otherwise, set them equal to "median"
    dfVar <- dfVar %>%
      mutate(stat = ifelse(date == d & shapiro_value >= 0.05,
                           "mean",
                           "median"))
  }
  
  dfVar <- dfVar %>%
    mutate(zscore = NA,
           zscore = ifelse(stat == "median" & mad_monthly > 0,
                           0.6745 * (var - mean_monthly) / mad_monthly,
                           zscore),
           zscore = ifelse(stat == "mean" & sd_monthly > 0,
                           (var - mean_monthly)/sd_monthly,
                           zscore),
           zscore = ifelse(stat == "mean" & sd_monthly <= 0,
                           0,
                           zscore), 
           zscore = ifelse(stat == "median" & mad_monthly <= 0 & sd_monthly > 0,
                           (var - mean_monthly)/sd_monthly,
                           zscore), 
           zscore = ifelse(stat == "median" & mad_monthly <= 0 & sd_monthly <= 0, 
                           0,
                           zscore))

  # if absolute value of z-score is greater than 2.00, then turn var value into NA; otherwise, leave as is
  dfVar <- dfVar %>%
    mutate(var = ifelse(abs(zscore) > 2.00,
                        NA,
                        var))
  
  var <- dfVar$var
  
  dfQC <- dfQC %>%
    cbind(var)
  
  colnames(dfQC)[colnames(dfQC) == "var"] = v
  }

```

### Save QC Data
```{r Save QC Data}
write_csv(dfQC, 
          file = "Data/CleanData/CleanDataYSI/02_QualityControl/QCOceanWaterQualityFrame.csv", 
          col_names = TRUE)
```


### Visualize QC Data Before Cutoffs Implemented
```{r Post-QC, Pre-Cutoffs Visualization}
OceanWaterQualityFramePivot <- dfQC %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))

AllVariablePlotPostQC <- OceanWaterQualityFramePivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Post-QC: Removed Values 2 Standard Deviations Outside Mean")+
  xlab("Date")+
  ylab("Nutrient Value")

AllVariablePlotPostQC

```


### Implement Cutoffs
```{r Implement Cutoffs}
# read in QCOceanWaterQualityFrame.csv that was created in a previous chunk
QCOceanWaterQualityFrame <- read_csv("Data/CleanData/CleanData_YSI/02_QualityControl/QCOceanWaterQualityFrame.csv")

# implement calibration cutoff values
CutQCOceanWaterQualityFrame <- QCOceanWaterQualityFrame %>%
  mutate(date = as.Date(date, format = "%m/%d/%Y")) %>%
  mutate(pH = ifelse(pH < 7.5, NA, pH)) %>%
  mutate(salinity_psu = ifelse(salinity_psu < 21, NA, salinity_psu)) %>%
  mutate(salinity_psu = ifelse(date > "2020/01/01" & salinity_psu < 31, NA, salinity_psu)) %>%
  mutate(salinity_psu = ifelse(date < "2013/01/01" & salinity_psu < 24, NA, salinity_psu)) %>%
  mutate(temp_c = ifelse(temp_c < 20 | temp_c > 28, NA, temp_c))

```


## Visualize Post-QC Data
```{r Visualize Post-QC, Post-Cutoff Data}
CutQCOceanWaterQualityFramePivot <- CutQCOceanWaterQualityFrame %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))

AllVariablePlotPostQCCutoff <- CutQCOceanWaterQualityFramePivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Post-QC: Removed Values 2 Standard Deviations Outside Mean and Cutoff Values")+
  xlab("Date")+
  ylab("Nutrient Value")

AllVariablePlotPostQCCutoff

```

# Write Post-QC CSV
```{r Write Post-QC csv}
write_csv(CutQCOceanWaterQualityFrame, 
          file = "Data/CleanData/CleanData_YSI/02_QualityControl/QCOceanWaterQualityFrame-Cutoff.csv", 
          col_names = TRUE)  

```

