---
title: "YSI Data Descriptive Statistics"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---
# Descriptive Statistics
## Import Libraries
```{r Import Libraries}
library(tidyverse)
library(tibbletime) 
options(scipen = 999)
```

## Import Data
Read in fully QC'd data
```{r Import Data}
df <- read_csv("Data/CleanData/CleanData_YSI/02_QualityControl/03-OceanWaterQualityData-QCCutoff.csv")

```

## Minor Data Manipulation
Add datetime column and create timetibble ordered by day
```{r data manip}
# combine date and time into datetime column 
dfEdit <- df %>%
  mutate(datetime = paste(date, time), .before = date,
         datetime = as.POSIXct(datetime)) %>% #make sure datetime is POSIXct class
  distinct() %>% #remove duplicate rows from df
  subset(is.na(datetime)==FALSE) #remove NAs from datetime
 
# inspect df to see what the classes of each column are
# str(dfEdit)

# create a time tibble and order by day for next steps
tbl <- as_tbl_time(dfEdit, index = datetime) %>%
  arrange(ymd_hms(datetime))

```

## Whole Time Series Statistics
```{r whole time series stats}

dfWhole <- dfEdit %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>%
  summarise(across(where(is.numeric), ~ min(.x, na.rm = TRUE)))
  
  
  
  
  data.frame(matrix(ncol = 6, nrow = 17))
colnames(dfWhole) <- c("variable", "min", "max", "mean", "median", "std")

var_names <- colnames(df)
var_names <- var_names[! var_names %in% c("date", "time")]

dfWhole <- dfWhole %>%
  mutate(variable = var_names,
         min = min())

# tblWhole <- tbl %>%
#   collapse_by("year") %>%
#   group_by(date) %>%
#   summarise_if(is.numeric, mean)

```


### Example code from Dan
```{r example code}
hoboph<- distinct(hoboph)#remove any duplicate rows
hoboph<-subset(hoboph,is.na(hoboph$Datetime)==FALSE) #remove any NAs

hoboph <- hoboph %>% 
  mutate_at(c(2:4), as.numeric) #make any columns that might be stuck as factors numeric
hoboph<-as_tbl_time(hoboph,index=Datetime) #create a time tibble
hobotbl<- hoboph %>% arrange(ymd_hms(hoboph$Datetime)) #order by day

#this syntax can be used to aggregate the data by all sorts of periods including week, hour, etc
hobophday<-hobotbl %>%
  collapse_by("day") %>%
  group_by(Datetime,Date)%>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))
```

