---
title: "B2O Hach Data Descriptive Statistics"
collaborators: Renee Grambihler
project: OceanWaterQuality
institution: Biosphere 2 Ocean
output: html_notebook
---
# Descriptive Statistics
## Import Libraries
```{r Import Libraries}
library(tidyverse)
library(tibbletime) 
library(lubridate)
options(scipen = 999)
```

# Import Data
Import fully QC'd data
```{r import data}
# use B2ONutrientdata-Clean-QC.csv
df <- read_csv("Data/Clean/Hach/02_QualityControl/02-Hach-Data-Clean-QC.csv")

```

## Minor Data Manipulation
Add datetime column and create timetibble ordered by day
```{r data manip}
dfPivot <- df %>%
  pivot_longer(cols = Turbidity:Ammonia,
               names_to = "nutrient",
               values_to = "nutrient_value")

# inspect df to see what the classes of each column are
# str(dfPivot)

```

## Whole Time Series Statistics
Summary statistics over entire time period of data
```{r whole time series stats}
dfWhole <- dfPivot %>%
  reframe(mean = mean(nutrient_value, na.rm = TRUE), 
          median = median(nutrient_value, na.rm = TRUE),
          std = sd(nutrient_value, na.rm = TRUE),
          IQR = IQR(nutrient_value, na.rm = TRUE),
          min = min(nutrient_value, na.rm = TRUE),
          max = max(nutrient_value, na.rm = TRUE),
          .by = c(Location, nutrient))%>%
   mutate(across(where(is.numeric), round, 2))

dfWhole[sapply(dfWhole, is.infinite)] <- NA #turn infinite values into NAs that were introduced when running min and max on variables that did not have any data

write_csv(dfWhole, "Data/Clean/Hach/03_DescriptiveStatistics/01-Hach-DescriptiveStats-Whole.csv")

```

## Yearly Statistics
Summary statistics by year
```{r stats by year}
dfYear <- dfPivot %>%
   mutate(date = format(Date, "%Y")) %>%
  reframe(mean = mean(nutrient_value, na.rm = TRUE), 
          median = median(nutrient_value, na.rm = TRUE),
          std = sd(nutrient_value, na.rm = TRUE),
          IQR = IQR(nutrient_value, na.rm = TRUE),
          Q1 = quantile(nutrient_value, 0.25, na.rm = TRUE), 
          Q3 = quantile(nutrient_value, 0.75, na.rm = TRUE),
          min = min(nutrient_value, na.rm = TRUE),
          max = max(nutrient_value, na.rm = TRUE),
          .by = c(date, Location, nutrient))%>%
  mutate(across(where(is.numeric), round, 2))

dfYear[sapply(dfYear, is.infinite)] <- NA #turn infinite values into NAs that were introduced when running min and max on variables that did not have any data

write_csv(dfYear, "Data/Clean/Hach/03_DescriptiveStatistics/02-Hach-DescriptiveStats-Yearly.csv")

```

## Monthly Statistics
Summary statistics by month
```{r stats by month}
dfMonth <- dfPivot %>%
  mutate(date = format(Date, "%Y-%m")) %>%
  reframe(mean = mean(nutrient_value, na.rm = TRUE), 
          median = median(nutrient_value, na.rm = TRUE),
          std = sd(nutrient_value, na.rm = TRUE),
          IQR = IQR(nutrient_value, na.rm = TRUE),
          min = min(nutrient_value, na.rm = TRUE),
          max = max(nutrient_value, na.rm = TRUE),
          .by = c(date, Location, nutrient))%>%
  mutate(across(where(is.numeric), round, 2))

dfMonth[sapply(dfMonth, is.infinite)] <- NA #turn infinite values into NAs that were introduced when running min and max on variables that did not have any data

write_csv(dfMonth, "Data/Clean/Hach/03_DescriptiveStatistics/03-Hach-DescriptiveStats-Monthly.csv")

```