---
title: "Ocean Data Plots"
Collaborators: Renee Grambihler
Project: OceanWaterQuality
Institution: Biosphere 2 Ocean
output: html_notebook
---

```{r Libraries}
library(tidyverse)
library(lubridate)
library(here)
```

# Import Data
```{r import data}
# Wrangled data before QC -- outliers still present
df <- read_csv(here("Data/CleanData/CleanDataYSI/01_DataWrangling/OceanWaterQualityFrame.csv"))

# Data after QC -- values outside of 2 sigma away from mean of every month for every variable were turned into NA values
dfQC <- read_csv(here("Data/CleanData/CleanDataYSI/02_QualityControl/QCOceanWaterQualityFrame.csv"))
```
# Data Formatting
```{r Pre-plotting Formatting}
# pivot df longer for easier all-variable plotting
dfPivot <- df %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))

# pivot dfQC longer for easier all-variable plotting
dfQCPivot <- dfQC %>%
  pivot_longer(cols = temp_f:total_dissolved_solids_mgL,
               names_to = "variable",
               values_to = "variable_value")%>%
  mutate(date = as.Date(date, format = "%Y/%m/%d"))


# df of mean value for each variable for each day
# QCMeanDailyValueFrame <- QCOceanWaterQualityFrame %>%
#   group_by(variable, date) %>%
#   summarise(mean_daily_value = mean(variable_value, na.rm = TRUE))

```

# Plotting
## Pre-QC Plots
```{r Basic plots - Pre QC}
# line graph of every variable - facet wrapped 
AllVariablePlot_PreQC <- dfPivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-PreQC.pdf", plot = AllVariablePlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots", height = 12, width = 10)

# line graph of temperature in fahrenheit
TempFPlot_PreQC <- dfPivot %>%
  filter(variable == "temp_f") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Temperature (ºF) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Temperature (ºF)")
# Save plot
ggsave(filename = "TempFPlot-PreQC.pdf", plot = TempFPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of temp in celcius
TempCPlot_PreQC <- dfPivot %>%
  filter(variable == "temp_c") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Temperature (ºC) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Temperature (ºC)")
# Save plot
ggsave(filename = "TempCPlot-PreQC.pdf", plot = TempCPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of pH in pH units
pHPlot_PreQC <- dfPivot %>%
  filter(variable == "pH") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O pH from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("pH")
# Save plot
ggsave(filename = "pHPlot-PreQC.pdf", plot = pHPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of pH in mV
pHmVPlot_PreQC <- dfPivot %>%
  filter(variable == "pH_mV") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O pH (mV) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("pH (mV)")
# Save plot
ggsave(filename = "pHmVPlot-PreQC.pdf", plot = pHmVPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of salinity in psu
SalinityPlot_PreQC <- dfPivot %>%
  filter(variable == "salinity_psu") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Salinity (PSU) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Salinity (PSU)")
# Save plot
ggsave(filename = "SalinityPlot-PreQC.pdf", plot = SalinityPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of conductivity in uS/cm
ConductivityPlot_PreQC <- dfPivot %>%
  filter(variable == "conductvity_uScm") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Conductivity (µS/cm) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Conductivity (µS/cm)")
# Save plot
ggsave(filename = "ConductivityPlot-PreQC.pdf", plot = ConductivityPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of nlf conductivity in uS/cm
NLFConductivityPlot_PreQC <- dfPivot %>%
  filter(variable == "nlf_conductivity_uScm") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O NLF Conductivity (µS/cm) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("NLF Conductivity (µS/cm)")
# Save plot
ggsave(filename = "NLFConductivityPlot-PreQC.pdf", plot = NLFConductivityPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of specific conductivity in uS/cm
SpConductivityPlot_PreQC <- dfPivot %>%
  filter(variable == "sp_conductivity_uScm") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Specific Conductivity (µS/cm) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Specific Conductivity (µS/cm)")
# Save plot
ggsave(filename = "SpConductivityPlot-PreQC.pdf", plot = SpConductivityPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of DO in mg/L
DOmgLPlot_PreQC <- dfPivot %>%
  filter(variable == "do_mgL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Dissolved Oxygen (mg/L) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Dissolved Oxygen (mg/L)")
# Save plot
ggsave(filename = "DOmgLPlot-PreQC.pdf", plot = DOmgLPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of DO in percent saturated
DOPercentSaturatedPlot_PreQC <- dfPivot %>%
  filter(variable == "do_saturated_percent") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Saturated Dissolved Oxygen (%) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Saturated Dissolved Oxygen (%)")
# Save plot
ggsave(filename = "DOPercentSaturatedPlot-PreQC.pdf", plot = DOPercentSaturatedPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of DO in percent local
DOPercentLocalPlot_PreQC <- dfPivot %>%
  filter(variable == "do_local_percent") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Local Dissolved Oxygen (%) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Local Dissolved Oxygen (%)")
# Save plot
ggsave(filename = "DOPercentLocalPlot-PreQC.pdf", plot = DOPercentLocalPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of ORP in mV
ORPPlot_PreQC <- dfPivot %>%
  filter(variable == "orp_mV") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O ORP (mV) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("ORP (mV)")
# Save plot
ggsave(filename = "ORPPlot-PreQC.pdf", plot = ORPPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of chlorophyll in RFU
ChlorophyllRFUPlot_PreQC <- dfPivot %>%
  filter(variable == "chlorophyll_rfu") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Chlorophyll (RFU) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Chlorophyll (RFU)")
# Save plot
ggsave(filename = "ChlorophyllRFUPlot-PreQC.pdf", plot = ChlorophyllRFUPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of chlorophyll in ug/L
ChlorophyllugLPlot_PreQC <- dfPivot %>%
  filter(variable == "chlorophyll_ugL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Chlorophyll (µg/L) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Chlorophyll (µg/L)")
# Save plot
ggsave(filename = "ChlorophyllugLPlot-PreQC.pdf", plot = ChlorophyllugLPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of total algae in cells/L
TotalAlgaePlot_PreQC <- dfPivot %>%
  filter(variable == "total_algae_cellsL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Total Algae (cells/L) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Total Algae (cells/L)")
# Save plot
ggsave(filename = "TotalAlgaePlot-PreQC.pdf", plot = TotalAlgaePlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")

# line graph of total dissolved solids in mg/L
TotalDissolvedSolidsPlot_PreQC <- dfPivot %>%
  filter(variable == "total_dissolved_solids_mgL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Total Dissolved Solids (mg/L) from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Total Dissolved Solids (mg/L)")
# Save plot
ggsave(filename = "TotalDissolvedSolidsPlot-PreQC.pdf", plot = TotalDissolvedSolidsPlot_PreQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PreQCPlots")


```

# Preliminary Plotting After Initial Standard Deviation QC
```{r Basic Plots - Post QC}
# line graph of every variable - facet wrapped 
AllVariablePlot_PostQC <- dfQCPivot %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality by Variable from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-PostQC.pdf", plot = AllVariablePlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots", height = 12, width = 10)

# line graph of temperature in fahrenheit
TempFPlot_PostQC <- dfQCPivot %>%
  filter(variable == "temp_f") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Temperature (ºF) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Temperature (ºF)")
# Save plot
ggsave(filename = "TempFPlot-PostQC.pdf", plot = TempFPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of temp in celcius
TempCPlot_PostQC <- dfQCPivot %>%
  filter(variable == "temp_c")%>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Temperature (ºC) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Temperature (ºC)")
# Save plot
ggsave(filename = "TempCPlot-PostQC.pdf", plot = TempCPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of pH in pH units
pHPlot_PostQC <- dfQCPivot %>%
  filter(variable == "pH") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O pH from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("pH")
# Save plot
ggsave(filename = "pHPlot-PostQC.pdf", plot = pHPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of pH in mV
pHmVPlot_PostQC <- dfQCPivot %>%
  filter(variable == "pH_mV") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O pH (mV) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("pH (mV)")
# Save plot
ggsave(filename = "pHmVPlot-PostQC.pdf", plot = pHmVPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of salinity in psu
SalinityPlot_PostQC <- dfQCPivot %>%
  filter(variable == "salinity_psu")%>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Salinity (PSU) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Salinity (PSU)")
# Save plot
ggsave(filename = "SalinityPlot-PostQC.pdf", plot = SalinityPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of conductivity in uS/cm
ConductivityPlot_PostQC <- dfQCPivot %>%
  filter(variable == "conductivity_uScm")%>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Conductivity (µS/cm) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Conductivity (µS/cm)")
# Save plot
ggsave(filename = "ConductivityPlot-PostQC.pdf", plot = ConductivityPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of nlf conductivity in uS/cm
NLFConductivityPlot_PostQC <- dfQCPivot %>%
  filter(variable == "nlf_conductivity_uScm") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O NLF Conductivity (µS/cm) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("NLF Conductivity (µS/cm)")
# Save plot
ggsave(filename = "NLFConductivityPlot-PostQC.pdf", plot = NLFConductivityPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of specific conductivity in uS/cm
SpConductivityPlot_PostQC <- dfQCPivot %>%
  filter(variable == "sp_conductivity_uScm") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Specific Conductivity (µS/cm) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Specific Conductivity (µS/cm)")
# Save plot
ggsave(filename = "SpConductivityPlot-PostQC.pdf", plot = SpConductivityPlot_PostQC,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of DO in mg/L
DOmgLPlot_PostQC <- dfQCPivot %>%
  filter(variable == "do_mgL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Dissolved Oxygen (mg/L) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Dissolved Oxygen (mg/L)")
# Save plot
ggsave(filename = "DOmgLPlot-PostQC.pdf", plot = DOmgLPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of DO in percent saturated
DOPercentSaturatedPlot_PostQC <- dfQCPivot %>%
  filter(variable == "do_saturated_percent") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Saturated Dissolved Oxygen (%) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Saturated Dissolved Oxygen (%)")
# Save plot
ggsave(filename = "DOPercentSaturatedPlot-PostQC.pdf", plot = DOPercentSaturatedPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of DO in percent local
DOPercentLocalPlot_PostQC <- dfQCPivot %>%
  filter(variable == "do_local_percent") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Local Dissolved Oxygen (%) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Local Dissolved Oxygen (%)")
# Save plot
ggsave(filename = "DOPercentLocalPlot-PostQC.pdf", plot = DOPercentLocalPlot_PostQC,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of ORP in mV
ORPPlot_PostQC <- dfQCPivot %>%
  filter(variable == "orp_mV") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O ORP (mV) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("ORP (mV)")
# Save plot
ggsave(filename = "ORPPlot-PostQC.pdf", plot = ORPPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of chlorophyll in RFU
ChlorophyllRFUPlot_PostQC <- dfQCPivot %>%
  filter(variable == "chlorophyll_rfu") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Chlorophyll (RFU) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Chlorophyll (RFU)")
# Save plot
ggsave(filename = "ChlorophyllRFUPlot-PostQC.pdf", plot = ChlorophyllRFUPlot_PostQC,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of chlorophyll in ug/L
ChlorophyllugLPlot_PostQC <- dfQCPivot %>%
  filter(variable == "chlorophyll_ugL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Chlorophyll (µg/L) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Chlorophyll (µg/L)")
# Save plot
ggsave(filename = "ChlorophyllugLPlot-PostQC.pdf", plot = ChlorophyllugLPlot_PostQC,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of total algae in cells/L
TotalAlgaePlot_PostQC <- dfQCPivot %>%
  filter(variable == "total_algae_cellsL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Total Algae (cells/L) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Total Algae (cells/L)")
# Save plot
ggsave(filename = "TotalAlgaePlot-PostQC.pdf", plot = TotalAlgaePlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")

# line graph of total dissolved solids in mg/L
TotalDissolvedSolidsPlot_PostQC <- dfQCPivot %>%
  filter(variable == "total_dissolved_solids_mgL") %>%
  ggplot(aes(x = date, 
             y = variable_value)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "1 year",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Total Dissolved Solids (mg/L) from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Total Dissolved Solids (mg/L)")
# Save plot
ggsave(filename = "TotalDissolvedSolidsPlot-PostQC.pdf", plot = TotalDissolvedSolidsPlot_PostQC, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/Figures/YSI-figures/PostQCPlots")
  
```

# Preliminary Plotting of Mean Daily Values After Initial Standard Deviation QC
```{r Basic Plots - Post QC Mean Daily Value}
# line graph of every variable - facet wrapped 
MDVAllVariablePlot <- MeanDailyValueFrame %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "12 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality Mean Daily Value by Variable from 2011-2023",
       subtitle = "Pre-QC: All Outliers Still Present")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-MDV.pdf", plot = MDVAllVariablePlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots", height = 12, width = 10)

# line graph of every variable - facet wrapped 
MDVPostQCAllVariablePlot <- QCMeanDailyValueFrame %>%
  ggplot(aes(x = date, 
             y = mean_daily_value)) +
  geom_line() +
  facet_wrap(~variable, ncol = 3, scales = "free")+
  scale_x_date(breaks = waiver(), date_breaks = "12 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "B2O Water Quality Mean Daily Value by Variable from 2011-2023",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")+
  xlab("Date")+
  ylab("Nutrient Value")
# Save plot
ggsave(filename = "AllVariablePlot-MDVPostQC.pdf", plot = MDVPostQCAllVariablePlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots", height = 12, width = 10)

# line graph of temperature in fahrenheit
MDVPostQCTempFPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "temp_f") %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Temperature (F)",
         title = "Post-QC B2O Temperature(F) Mean Daily Value from 2011-2023")
MDVPostQCTempFPlot
# Save plot
ggsave(filename = "TempFPlot-MDVPostQC.pdf", plot = MDVPostQCTempFPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of temp in celcius
MDVPostQCTempCPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "temp_c")%>%
  filter(mean_daily_value > 19 & mean_daily_value < 28) %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Temperature (C)",
         title = "Post-QC B2O Temperature(C) Mean Daily Value from 2011-2023")
MDVPostQCTempCPlot
# Save plot
ggsave(filename = "TempCPlot-MDVPostQC.pdf", plot = MDVPostQCTempCPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of pH in pH units
MDVPostQCpHPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "pH") %>%
  filter(mean_daily_value > 7 & mean_daily_value < 10) %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "pH",
         title = "Post-QC B2O pH Mean Daily Value from 2011-2023")
MDVPostQCpHPlot
# Save plot
ggsave(filename = "pHPlot-MDVPostQC.pdf", plot = MDVPostQCpHPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of pH in mV
MDVPostQCpHmVPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "pH_mV") %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "pH (mV)",
         title = "Post-QC B2O pH(mV) Mean Daily Value from 2011-2023")
MDVPostQCpHmVPlot
# Save plot
ggsave(filename = "pHmVPlot-MDVPostQC.pdf", plot = MDVPostQCpHmVPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of salinity in psu
MDVPostQCSalinityPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "salinity_psu")%>%
  filter(mean_daily_value > 20)%>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Salinity (PSU)",
         title = "PostQC B2O Salinity(PSU) Mean Daily Value from 2011-2023")
MDVPostQCSalinityPlot
# Save plot
ggsave(filename = "SalinityPlot-MDVPostQC.pdf", plot = MDVPostQCSalinityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of conductivity in uS/cm
MDVPostQCConductivityPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "conductivity_uScm")%>%
  filter(mean_daily_value > 30000)%>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Conductivity(uS/cm)",
         title = "Post-QC B2O Conductivity(uS/cm) Mean Daily Value from 2011-2023")
MDVPostQCConductivityPlot
# Save plot
ggsave(filename = "ConductivityPlot-MDVPostQC.pdf", plot = MDVPostQCConductivityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of nlf conductivity in uS/cm
MDVPostQCNLFConductivityPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "nlf_conductivity_uScm") %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "NLF Conductivity(uS/cm)",
         title = "Post-QC B2O NLF Conductivity(uS/cm) Mean Daily Value from 2011-2023")
MDVPostQCNLFConductivityPlot
# Save plot
ggsave(filename = "NLFConductivityPlot-MDVPostQC.pdf", plot = MDVPostQCNLFConductivityPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of specific conductivity in uS/cm
MDVPostQCSpConductivityPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "sp_conductivity_uScm") %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Specific Conductivity(uS/cm)",
         title = "Post-QC B2O Specific Conductivity(uS/cm) Mean Daily Value from 2011-2023")
MDVPostQCSpConductivityPlot
# Save plot
ggsave(filename = "SpConductivityPlot-MDVPostQC.pdf", plot = PostQCSpConductivityPlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of DO in mg/L
MDVPostQCDOmgLPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "do_mgL") %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Dissolved Oxygen(mg/L)",
         title = "Post-QC B2O Dissolved Oxygen(mg/L) Mean Daily Value from 2021-2023")
MDVPostQCDOmgLPlot
# Save plot
ggsave(filename = "DOmgLPlot-MDVPostQC.pdf", plot = MDVPostQCDOmgLPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of DO in percent saturated
MDVPostQCDOPercentSaturatedPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "do_saturated_percent") %>%
  filter(mean_daily_value < 100) %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Dissolved Oxygen Percent Saturated",
         title = "Post-QC B2O Dissolved Oxygen Percent Saturated Mean Daily Value from 2019-2023")
MDVPostQCDOPercentSaturatedPlot
# Save plot
ggsave(filename = "DOPercentSaturatedPlot-MDVPostQC.pdf", plot = MDVPostQCDOPercentSaturatedPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of DO in percent local
MDVPostQCDOPercentLocalPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "do_local_percent") %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Dissolved Oxygen Percent Local",
         title = "Post-QC B2O Dissolved Oxygen Percent Local Mean Daily Value from 2011-2023")
MDVPostQCDOPercentLocalPlot
# Save plot
ggsave(filename = "DOPercentLocalPlot-MDVPostQC.pdf", plot = MDVPostQCDOPercentLocalPlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of ORP in mV
MDVPostQCORPPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "orp_mV") %>%
  filter(mean_daily_value > 0)%>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "ORP(mV)",
         title = "Post-QC B2O Oxidation-Reduction Potential(mV) Mean Daily Value from 2011-2023")
MDVPostQCORPPlot
# Save plot
ggsave(filename = "ORPPlot-MDVPostQC.pdf", plot = MDVPostQCORPPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of chlorophyll in RFU
MDVPostQCChlorophyllRFUPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "chlorophyll_rfu") %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Chlorophyll(RFU)",
         title = "Post-QC B2O Chlorophyll(RFU) Mean Daily Value from 2021-2023")
MDVPostQCChlorophyllRFUPlot
# Save plot
ggsave(filename = "ChlorophyllRFUPlot-MDVPostQC.pdf", plot = MDVPostQCChlorophyllRFUPlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of chlorophyll in ug/L
MDVPostQCChlorophyllugLPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "chlorophyll_ugL") %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Chlorophyll(ug/L)",
         title = "Post-QC B2O Chlorophyll(ug/L) Mean Daily Value from 2011-2023")
MDVPostQCChlorophyllugLPlot
# Save plot
ggsave(filename = "ChlorophyllugLPlot-MDVPostQC.pdf", plot = MDVPostQCChlorophyllugLPlot,
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of total algae in cells/L
MDVPostQCTotalAlgaePlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "total_algae_cellsL") %>%
  filter(mean_daily_value > 0) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Total Algae(cells/L)",
         title = "Post-QC B2O Total Algae(cells/L) Mean Daily Value from 2011-2023")+
  scale_x_date(date_labels = "%m-%d-%Y")
MDVPostQCTotalAlgaePlot
# Save plot
ggsave(filename = "TotalAlgaePlot-MDVPostQC.pdf", plot = MDVPostQCTotalAlgaePlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of total dissolved solids in mg/L
MDVPostQCTotalDissolvedSolidsPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "total_dissolved_solids_mgL") %>%
  na.omit() %>%
  remove_sd_outlier(cols = "mean_daily_value", 
                    n_sigmas = 2) %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "Total Dissolved Solids(mg/L)",
         title = "Post-QC B2O Total Dissolved Solids(mg/L) Mean Daily Value from 2021-2023")
MDVPostQCTotalDissolvedSolidsPlot
# Save plot
ggsave(filename = "TotalDissolvedSolidsPlot-MDVPostQC.pdf", plot = MDVPostQCTotalDissolvedSolidsPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")

# line graph of RO flow in gallons/min
MDVPostQCROFlowPlot <- SDMeanDailyValueFrameFull %>%
  filter(variable == "ro_flow_gpm") %>%
  ggline(x = "date",
         y = "mean_daily_value",
         plot_type = "l",
         xlab = "Date",
         ylab = "RO Flow(gallons/minute)",
         title = "Post-QC B2O RO Flow(gallons/minute) Mean Daily Value from 2011-2023")
MDVPostQCROFlowPlot
# Save plot
ggsave(filename = "ROFlowPlot-MDVPostQC.pdf", plot = MDVPostQCROFlowPlot, 
       path = "/Users/grambihler/Documents/Data/GitHub/OceanWaterQuality/YSIExoSonde/YSI-figures/MDVPostQCPlots")
  
```
