---
title: "HACH Nutrient Data Figures: Post Quality Control"
Collaborators: Renee Grambihler
Project: "Ocean Water Quality"
Institution: Biosphere 2 Ocean
---

# Libraries
```{r libraries}
library(tidyverse)
library(lubridate)
# remove scientific notation
options(scipen = 999)
```

# Import Data
```{r import data}
# use B2ONutrientData-Clean-QC.csv
dfQC <- read_csv("Data/CleanData/CleanData_Nutrients/B2ONutrientData-Clean-QC.csv")

```

# Data Formatting
```{r data formatting}
# make long format data frame for plots showing all nutrients at a location (faceted)
dfQCPivot <- dfQC %>%
   pivot_longer(cols = Turbidity:Ammonia,
               names_to = "Nutrients",
               values_to = "Nutrient Values")

```

# Post-Quality Control Data Visualizations by Location
```{r Post-QC Visualizations}
# All Locations Plot
PostQCAllLocationsPlot <- dfQCPivot %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`, 
             color = Location)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Nutrients for Ocean, Raceways, and Mangrove Mesocosms from 2018-Present",
          subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# Save Plot
ggsave(filename = "AllLocationsPlot-PostQC.pdf", 
       plot = PostQCAllLocationsPlot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots",
       width = 10, height = 7)

# Ocean Plot
PostQCOceanPlot <- dfQCPivot %>%
  filter(Location == "Ocean") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Ocean Nutrients from 2019-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot
ggsave(filename = "OceanPlot-PostQC.pdf", plot = PostQCOceanPlot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots/Ocean", width = 10, height = 7)

# Raceway 1 Plot
PostQCRaceway1Plot <- dfQCPivot %>%
  filter(Location == "Raceway 1") %>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Coral Raceway 1 Nutrients 2020-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway1Plot-PostQC.pdf", 
       plot = PostQCRaceway1Plot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots/Raceways/Raceway1", width = 10, height = 7)

# Raceway 2 Plot
PostQCRaceway2Plot <- dfQCPivot %>%
  filter(Location == "Raceway 2") %>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "2 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Coral Raceway 2 Nutrients From 2021 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway2Plot-PostQC.pdf", 
       plot = PostQCRaceway2Plot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots/Raceways/Raceway2", width = 10, height = 7)

# Mangrove Plot
PostQCMangrovePlot <- dfQCPivot %>%
  filter(Location == "Mangroves") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Mangrove Nutrients from 2018-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot
ggsave(filename = "MangrovePlot-PostQC.pdf", 
       plot = PostQCMangrovePlot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots/Mangroves", width = 10, height = 7)

# Raceways 1 and 2 Plot
PostQCRaceway1Raceway2Plot <- dfQCPivot %>%
  filter(Location == "Raceway 1" | Location == "Raceway 2")%>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`,
             color = Location)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Raceways 1 and 2 Nutrients From 2020 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway1Raceway2Plot-PostQC.pdf", 
       plot = PostQCRaceway1Raceway2Plot,
       path = "Figures/Figures_NutrientData/02-PostQCPlots/Raceways/BothRaceways", width = 10, height = 7)

```

# Plots for fun
```{r more plots}
dfQC %>%
  filter(Location == "Raceway 1" | Location == "Raceway 2")%>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = Ammonia,
             color = Location)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Raceways 1 and 2 Nutrients From 2020 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")

dfQCAmmonia <- dfQC %>%
  select(Date, Location, Ammonia) %>%
  mutate(Date = as.Date(Date))

dfQCAmmonia %>%
  filter(Location == "Raceway 1" | Location == "Raceway 2")%>%
  filter(Date > "2022-09-01") %>%
  na.omit() %>%
  ggplot(aes(x = Date,
             y = Ammonia,
             color = Location)) +
  geom_line() +
  scale_x_date(breaks = waiver(), date_breaks = "2 months",
               date_labels = "%b %Y") +
  labs(title = "Biosphere 2 Raceways 1 and 2 Nutrients From 2020 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")

```

