---
title: "HACH Data Figures: Post Quality Control"
Collaborators: Renee Grambihler
Project: "Ocean Water Quality"
Institution: Biosphere 2 Ocean
---

# Libraries
```{r libraries}
library(tidyverse)
library(lubridate)
# remove scientific notation
options(scipen = 999)
```

# Import Data
```{r import data}
# use 02-Hach-Data-Clean-QC.csv
df <- read_csv("Data/Clean/Hach/02_QualityControl/02-Hach-Data-Clean-QC.csv")

```

# Data Formatting
```{r data formatting}
# make long format data frame for plots showing all nutrients at a location (faceted)
dfPivot <- df %>%
   pivot_longer(cols = Turbidity:Ammonia,
               names_to = "Nutrients",
               values_to = "Nutrient Values") %>%
  na.omit()

```

# Post-Quality Control Data Visualizations by Location
## Plots Faceted by Nutrient
### All Locations
```{r All Nutrients: All Locations}
# All Locations Plot
PostQCAllLocationsPlot <- dfPivot %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`, 
             color = Location)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Nutrients for Ocean, Raceways, and Mangrove Mesocosms from 2018-Present",
          subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# Save Plot
ggsave(filename = "AllLocationsPlot-PostQC.pdf", 
       plot = PostQCAllLocationsPlot,
       path = "Figures/Hach/02_PostQC",
       width = 10, height = 7)
```
### Ocean
```{r All Nutrients: Ocean Plot}
# Ocean Plot
PostQCOceanPlot <- dfPivot %>%
  filter(Location == "Ocean") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Ocean Nutrients from 2019-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot
ggsave(filename = "OceanPlot-PostQC.pdf", plot = PostQCOceanPlot,
       path = "Figures/Hach/02_PostQC/Ocean", width = 10, height = 7)
```
### Raceway 1
```{r All Nutrients: Raceway 1 Plot}
# Raceway 1 Plot
PostQCRaceway1Plot <- dfPivot %>%
  filter(Location == "Raceway 1") %>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Coral Raceway 1 Nutrients 2020-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway1Plot-PostQC.pdf", 
       plot = PostQCRaceway1Plot,
       path = "Figures/Hach/02_PostQC/Raceways/Raceway1", width = 10, height = 7)
```
### Raceway 2
```{r All Nutrients: Raceway 2}
# Raceway 2 Plot
PostQCRaceway2Plot <- dfPivot %>%
  filter(Location == "Raceway 2") %>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "2 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Coral Raceway 2 Nutrients From 2021 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway2Plot-PostQC.pdf", 
       plot = PostQCRaceway2Plot,
       path = "Figures/Hach/02_PostQC/Raceways/Raceway2", width = 10, height = 7)
```
### Mangroves
```{r All Nutrients: Mangroves}
# Mangrove Plot
PostQCMangrovePlot <- dfPivot %>%
  filter(Location == "Mangroves") %>% 
  filter(Nutrients != "Iron" & Nutrients != "Silica") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Mangrove Nutrients from 2018-Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot
ggsave(filename = "MangrovePlot-PostQC.pdf", 
       plot = PostQCMangrovePlot,
       path = "Figures/Hach/02_PostQC/Mangroves", width = 10, height = 7)
```
### Both Raceways
```{r All Nutrients: All Raceways}
# Raceways 1 and 2 Plot
PostQCRaceway1Raceway2Plot <- dfPivot %>%
  filter(Location == "Raceway 1" | Location == "Raceway 2")%>%
  filter(Date > "2020-04-01") %>%
  ggplot(aes(x = Date,
             y = `Nutrient Values`,
             color = Location)) +
  geom_line() +
  facet_wrap(~Nutrients, ncol = 3, scales = "free") +
  scale_x_date(breaks = waiver(), date_breaks = "6 months",
               date_labels = "%b %Y") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))+
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
  theme(strip.background = element_rect(fill = "white"))+
  labs(title = "Biosphere 2 Raceways 1 and 2 Nutrients From 2020 to Present",
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed")
# save plot 
ggsave(filename = "Raceway1Raceway2Plot-PostQC.pdf", 
       plot = PostQCRaceway1Raceway2Plot,
       path = "Figures/Hach/02_PostQC/Raceways/BothRaceways", width = 10, height = 7)

```

## Plots with One Nutrient Per Plot
### Set-Up for Loops
```{r loop set-up}
# set up vectors to use in loops below
# name of each nutrient
nutrient_names <- unique(dfPivot$Nutrients)
# name of each location
location_names <- unique(dfPivot$Location)
# text to use in each plot title for each nutrient
nutrient_text <- c("Nitrate MR (mg/L)", "Nitrate HR (mg/L)", "Turbidity (FAU)", "Phosphate (mg/L)",
                   "pH", "Silica (mg/L)", "Alkalinity mg/L", "Iron (mg/L)", "Ammonia (mg/L)")
# file name for each plot
file_names <- c("NitrateMRPlot", "NitrateHRPlot", "TurbidityPlot", "PhosphatePlot", "pHPlot",
                "SilicaPlot", "AlkalinityPlot", "IronPlot", "AmmoniaPlot")

```
### Line Graphs
#### Time Series
```{r Line Graphs, Time Series}
# loop through each location, loop through each nutrient at each location, plot simple line graph of entire time series, save plot
# list to save plots from all locations into
plotList <- list()
# loop through each location
for (l in 1:length(location_names)) {
  # list to save plots of each nutrient into for one location
  plotList_location <- list()
  # loop through each nutrient
  for (i in 1:length(nutrient_names)) {
    dfLoop <- dfPivot %>%
      filter(Location == location_names[l]) %>% #filter by current location in loop
      filter(Nutrients == nutrient_names[i]) #filter by current nutrient in location in loop
    #skip iteration if nutrient has 1 or less data points in order to avoid creating blank plots
    if (length(dfLoop$Nutrients) <= 1) next 
    # create plot in space i of plotList_location
    plotList_location[[i]] <- dfLoop %>%
      ggplot(aes(x = Date,
                 y = `Nutrient Values`)) +
      geom_line() +
      scale_x_date(date_labels = "%b %Y", 
                   # if there are 12 or fewer months of data, label every 2 months, otherwise do every 4
                   date_breaks = ifelse(interval(dfLoop$Date[1], tail(dfLoop$Date, n = 1)) %/% months(1) <= 12,
                                        "2 months",
                                        "4 months")) +
      # theme code is for making background of plot nice
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(colour = "black"))+
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
      theme(strip.background = element_rect(fill = "white"))+
      labs(title = paste("Biosphere 2", location_names[l], nutrient_text[i], "from 2018-2023"),
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
       x = "Date",
       y = nutrient_text[i])
    print(plotList_location[[i]]) #makes quick to look at in RStudio
    # Save plot
    ggsave(plot = plotList_location[[i]],
           filename = paste(location_names[l],file_names[i],"PostQC-Line-TimeSeries.pdf", 
                            sep = "-"),
           path = paste("Figures/Hach/02_PostQC",location_names[l],"LineGraphs/TimeSeries", 
                        sep = "/"))
  }
  # add plotList_location to plotList
  plotList <- c(plotList, plotList_location)
}

```
#### Seasonal
```{r Line Graphs, Seasonal}
# loop through each location, loop through each nutrient at each location, plot line graph showing data for each year stacked on same plot, save plot
# list to save plots from all locations into
plotList <- list()
# loop through each location
for (l in 1:length(location_names)) {
  # list to save plots of each nutrient into for one location
  plotList_location <- list()
  # loop through each nutrient
  for (i in 1:length(nutrient_names)) {
    dfLoop <- dfPivot %>%
      filter(Location == location_names[l]) %>% #filter by current location in loop
      filter(Nutrients == nutrient_names[i]) #filter by current nutrient in location in loop
    #skip iteration if nutrient has 1 or less data points in order to avoid creating blank plots
    if (length(dfLoop$Nutrients) <= 1) next 
    # create plot in space i of plotList_location
    plotList_location[[i]] <- dfLoop %>%
      ggplot(aes(x = as.Date(yday(Date), "2021-01-01"), #use each day of the year as the x axis data
                 color = factor(year(Date)), #plot data from each year separately as its own color
                 y = `Nutrient Values`)) + #use nutrient values as y axis data
      geom_line() +
      scale_x_date(date_breaks = "months", date_labels = "%b") +
      # theme code is for making background of plot nice
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(colour = "black"))+
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
      theme(strip.background = element_rect(fill = "white"))+
      labs(title = paste("Biosphere 2", location_names[l], nutrient_text[i], "from 2018-2023"),
           subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
           x = "Date",
           y = nutrient_text[i],
           color = "Year")
    print(plotList_location[[i]]) #makes quick to look at in RStudio
    # Save plot
    ggsave(plot = plotList_location[[i]],
           filename = paste(location_names[l],file_names[i],"PostQC-Line-Seasonal.pdf", 
                            sep = "-"),
           path = paste("Figures/Hach/02_PostQC",location_names[l],"LineGraphs/Seasonal", 
                        sep = "/"))
  }
  # add plotList_location to plotList
  plotList <- c(plotList, plotList_location)
}

```
### Loess Graphs
#### Time Series
```{r Loess Graphs, Time Series}
# loop through each location, loop through each nutrient at each location, plot loess line graph of entire time series, save plot
# list to save plots from all locations into
plotList <- list()
# loop through each location
for (l in 1:length(location_names)) {
  # list to save plots of each nutrient into for one location
  plotList_location <- list()
  # loop through each nutrient
  for (i in 1:length(nutrient_names)) {
    dfLoop <- dfPivot %>%
      filter(Location == location_names[l]) %>% #filter by current location in loop
      filter(Nutrients == nutrient_names[i]) #filter by current nutrient in location in loop
    #skip iteration if nutrient has 1 or less data points in order to avoid creating blank plots
    if (length(dfLoop$Nutrients) <= 1) next 
    # create plot in space i of plotList_location
    plotList_location[[i]] <- dfLoop %>%
      ggplot(aes(x = Date,
                 y = `Nutrient Values`)) +
      geom_line() +
      geom_smooth() +
      scale_x_date(date_labels = "%b %Y", 
                   # if there are 12 or fewer months of data, label every 2 months, otherwise do every 4
                   date_breaks = ifelse(interval(dfLoop$Date[1], tail(dfLoop$Date, n = 1)) %/% months(1) <= 12,
                                        "2 months",
                                        "4 months")) +
      # theme code is for making background of plot nice
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(colour = "black"))+
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
      theme(strip.background = element_rect(fill = "white"))+
      labs(title = paste("Biosphere 2", location_names[l], nutrient_text[i], "from 2018-2023"),
       subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
       x = "Date",
       y = nutrient_text[i])
    print(plotList_location[[i]]) #makes quick to look at in RStudio
    # Save plot
    ggsave(plot = plotList_location[[i]],
           filename = paste(location_names[l],file_names[i],"PostQC-Loess-TimeSeries.pdf", 
                            sep = "-"),
           path = paste("Figures/Hach/02_PostQC",location_names[l],"LoessGraphs/TimeSeries", 
                        sep = "/"))
  }
  # add plotList_location to plotList
  plotList <- c(plotList, plotList_location)
}

```
#### Seasonal
```{r Loess Graphs, Seasonal}
# loop through each location, loop through each nutrient at each location, plot loess line graph showing data for each year stacked on same plot, save plot
# list to save plots from all locations into
plotList <- list()
# loop through each location
for (l in 1:length(location_names)) {
  # list to save plots of each nutrient into for one location
  plotList_location <- list()
  # loop through each nutrient
  for (i in 1:length(nutrient_names)) {
    dfLoop <- dfPivot %>%
      filter(Location == location_names[l]) %>% #filter by current location in loop
      filter(Nutrients == nutrient_names[i]) #filter by current nutrient in location in loop
    #skip iteration if nutrient has 1 or less data points in order to avoid creating blank plots
    if (length(dfLoop$Nutrients) <= 1) next 
    # create plot in space i of plotList_location
    plotList_location[[i]] <- dfLoop %>%
      ggplot(aes(x = as.Date(yday(Date), "2021-01-01"), #use each day of the year as the x axis data
                 color = factor(year(Date)), #plot data from each year separately as its own color
                 y = `Nutrient Values`)) + #use nutrient values as y axis data
      geom_smooth() +
      scale_x_date(date_breaks = "months", date_labels = "%b") +
      # theme code is for making background of plot nice
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(colour = "black"))+
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            plot.margin = margin(0.25, 0.45, 0.25, 0.25, "inch"))+
      theme(strip.background = element_rect(fill = "white"))+
      labs(title = paste("Biosphere 2", location_names[l], nutrient_text[i], "from 2018-2023"),
           subtitle = "Post-QC: Data Outside 2-Sigma from Mean has been Removed", 
           x = "Date",
           y = nutrient_text[i],
           color = "Year")
    print(plotList_location[[i]]) #makes quick to look at in RStudio
    # Save plot
    ggsave(plot = plotList_location[[i]],
           filename = paste(location_names[l],file_names[i],"PostQC-Loess-Seasonal.pdf", 
                            sep = "-"),
           path = paste("Figures/Hach/02_PostQC",location_names[l],"LoessGraphs/Seasonal", 
                        sep = "/"))
  }
  # add plotList_location to plotList
  plotList <- c(plotList, plotList_location)
}

```


